window.CL_CDC = `
<div class="cl-native-content">
<h2 class="cl-part">POLÍTICA NACIONAL DAS RELAÇÕES DE CONSUMO</h2>
<p class="cl-texto">(CONCEITO DE CONSUMIDOR) Art. 2° CDC. Consumidor é toda pessoa física ou jurídica que adquire ou utiliza produto ou serviço como destinatário final. \<span class="cl-oab-badge">Caiu OAB 30</span>*</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Equipara-se a consumidor a coletividade de pessoas, ainda que indetermináveis, que haja intervindo nas relações de consumo.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 3° CDC.</strong> <span class="cl-art-texto">Fornecedor é toda pessoa física ou jurídica, pública ou privada, nacional ou estrangeira, bem como os entes despersonalizados, que desenvolvem atividade de produção, montagem, criação, construção, transformação, importação, exportação, distribuição ou comercialização de produtos ou prestação de serviços.</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> Produto é qualquer bem, móvel ou imóvel, material ou imaterial.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Serviço é qualquer atividade fornecida no mercado de consumo, mediante remuneração, inclusive as de natureza bancária, financeira, de crédito e securitária, salvo as decorrentes das relações de caráter trabalhista.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 4º CDC.</strong> <span class="cl-art-texto">A Política Nacional das Relações de Consumo tem por objetivo o atendimento das necessidades dos consumidores, o respeito à sua dignidade, saúde e segurança, a proteção de seus interesses econômicos, a melhoria da sua qualidade de vida, bem como a transparência e harmonia das relações de consumo, atendidos os seguintes princípios:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>reconhecimento da vulnerabilidade do consumidor no mercado de consumo;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>ação governamental no sentido de proteger efetivamente o consumidor:</p>
<p class="cl-alinea">a) por iniciativa direta;</p>
<p class="cl-alinea">b) por incentivos à criação e desenvolvimento de associações representativas;</p>
<p class="cl-alinea">c) pela presença do Estado no mercado de consumo;</p>
<p class="cl-alinea">d) pela garantia dos produtos e serviços com padrões adequados de qualidade, segurança, durabilidade e desempenho.</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>harmonização dos interesses dos participantes das relações de consumo e compatibilização da proteção do consumidor com a necessidade de desenvolvimento econômico e tecnológico, de modo a viabilizar os princípios nos quais se funda a ordem econômica (art. 170, da Constituição Federal), sempre com base na boa-fé e equilíbrio nas relações entre consumidores e fornecedores;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>educação e informação de fornecedores e consumidores, quanto aos seus direitos e deveres, com vistas à melhoria do mercado de consumo;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>incentivo à criação pelos fornecedores de meios eficientes de controle de qualidade e segurança de produtos e serviços, assim como de mecanismos alternativos de solução de conflitos de consumo;</p>
<p class="cl-inciso"><span class="cl-inc-num">VI –</span>coibição e repressão eficientes de todos os abusos praticados no mercado de consumo, inclusive a concorrência desleal e utilização indevida de inventos e criações industriais das marcas e nomes comerciais e signos distintivos, que possam causar prejuízos aos consumidores;</p>
<p class="cl-inciso"><span class="cl-inc-num">VII –</span>racionalização e melhoria dos serviços públicos;</p>
<p class="cl-inciso"><span class="cl-inc-num">VIII –</span>estudo constante das modificações do mercado de consumo.</p>
<p class="cl-texto">IX - fomento de ações direcionadas à educação financeira e ambiental dos consumidores; (Incluído pela Lei nº 14.181, de 2021)</p>
<p class="cl-inciso"><span class="cl-inc-num">X –</span>prevenção e tratamento do superendividamento como forma de evitar a exclusão social do consumidor. (Incluído pela Lei nº 14.181, de 2021)</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 5° CDC.</strong> <span class="cl-art-texto">Para a execução da Política Nacional das Relações de Consumo, contará o poder público com os seguintes instrumentos, entre outros:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>manutenção de assistência jurídica, integral e gratuita para o consumidor carente;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>instituição de Promotorias de Justiça de Defesa do Consumidor, no âmbito do Ministério Público;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>criação de delegacias de polícia especializadas no atendimento de consumidores vítimas de infrações penais de consumo;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>criação de Juizados Especiais de Pequenas Causas e Varas Especializadas para a solução de litígios de consumo;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>concessão de estímulos à criação e desenvolvimento das Associações de Defesa do Consumidor.</p>
<p class="cl-inciso"><span class="cl-inc-num">VI –</span>instituição de mecanismos de prevenção e tratamento extrajudicial e judicial do superendividamento e de proteção do consumidor pessoa natural; (Incluído pela Lei nº 14.181, de 2021)</p>
<p class="cl-inciso"><span class="cl-inc-num">VII –</span>instituição de núcleos de conciliação e mediação de conflitos oriundos de superendividamento. (Incluído pela Lei nº 14.181, de 2021)</p>
<p class="cl-texto">(CONSUMIDOR POR EQUIPARAÇÃO) Art. 17 CDC. Para os efeitos desta Seção, equiparam-se aos consumidores todas as vítimas do evento.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 29 CDC.</strong> <span class="cl-art-texto">Para os fins deste Capítulo e do seguinte, equiparam-se aos consumidores todas as pessoas determináveis ou não, expostas às práticas nele previstas.</span></div>
<p class="cl-texto">SÚMULA 563 STJ - O Código de Defesa do Consumidor é aplicável às entidades abertas de previdência complementar, não incidindo nos contratos previdenciários.</p>
<p class="cl-texto">SÚMULA 608 STJ - Aplica-se o Código de Defesa do Consumidor aos contratos de plano de saúde, salvo os administrados por entidades de autogestão.</p>
<h2 class="cl-part">DIREITOS DO CONSUMIDOR</h2>
<p class="cl-texto">(CONCEITO DE CONSUMIDOR) Art. 2° CDC. Consumidor é toda pessoa física ou jurídica que adquire ou utiliza produto ou serviço como destinatário final. \<span class="cl-oab-badge">Caiu OAB 30</span>*</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Equipara-se a consumidor a coletividade de pessoas, ainda que indetermináveis, que haja intervindo nas relações de consumo.</p>
<p class="cl-texto">(CONCEITO DE FORNECEDOR) Art. 3° CDC. Fornecedor é toda pessoa física ou jurídica, pública ou privada, nacional ou estrangeira, bem como os entes despersonalizados, que desenvolvem atividade de produção, montagem, criação, construção, transformação, importação, exportação, distribuição ou comercialização de produtos ou prestação de serviços.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> Produto é qualquer bem, móvel ou imóvel, material ou imaterial.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Serviço é qualquer atividade fornecida no mercado de consumo, mediante remuneração, inclusive as de natureza bancária, financeira, de crédito e securitária, salvo as decorrentes das relações de caráter trabalhista.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 6 CDC.</strong> <span class="cl-art-texto">São direitos básicos do consumidor:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>a proteção da vida, saúde e segurança contra os riscos provocados por práticas no fornecimento de produtos e serviços considerados perigosos ou nocivos;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a educação e divulgação sobre o consumo adequado dos produtos e serviços, asseguradas a liberdade de escolha e a igualdade nas contratações;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>a informação adequada e clara sobre os diferentes produtos e serviços, com especificação correta de quantidade, características, composição, qualidade, tributos incidentes e preço, bem como sobre os riscos que apresentem; \<span class="cl-oab-badge">Caiu OAB 29</span>* \<span class="cl-oab-badge">Caiu OAB 28</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>a proteção contra a publicidade enganosa e abusiva, métodos comerciais coercitivos ou desleais, bem como contra práticas e cláusulas abusivas ou impostas no fornecimento de produtos e serviços; \<span class="cl-oab-badge">Caiu OAB 41</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>a modificação das cláusulas contratuais que estabeleçam prestações desproporcionais ou sua revisão em razão de fatos supervenientes que as tornem excessivamente onerosas;</p>
<p class="cl-inciso"><span class="cl-inc-num">VI –</span>a efetiva prevenção e reparação de danos patrimoniais e morais, individuais, coletivos e difusos;</p>
<p class="cl-inciso"><span class="cl-inc-num">VII –</span>o acesso aos órgãos judiciários e administrativos com vistas à prevenção ou reparação de danos patrimoniais e morais, individuais, coletivos ou difusos, assegurada a proteção Jurídica, administrativa e técnica aos necessitados;</p>
<p class="cl-inciso"><span class="cl-inc-num">VIII –</span>a facilitação da defesa de seus direitos, inclusive com a inversão do ônus da prova, a seu favor, no processo civil, quando, a critério do juiz, for verossímil a alegação ou quando for ele hipossuficiente, segundo as regras ordinárias de experiências;</p>
<p class="cl-inciso"><span class="cl-inc-num">IX –</span>(Vetado);</p>
<p class="cl-inciso"><span class="cl-inc-num">X –</span>a adequada e eficaz prestação dos serviços públicos em geral.</p>
<p class="cl-inciso"><span class="cl-inc-num">XI –</span>a garantia de práticas de crédito responsável, de educação financeira e de prevenção e tratamento de situações de superendividamento, preservado o mínimo existencial, nos termos da regulamentação, por meio da revisão e da repactuação da dívida, entre outras medidas; \<span class="cl-oab-badge">Caiu OAB 41</span>*</p>
<p class="cl-texto">XII - a preservação do mínimo existencial, nos termos da regulamentação, na repactuação de dívidas e na concessão de crédito;</p>
<p class="cl-inciso"><span class="cl-inc-num">XIII –</span>a informação acerca dos preços dos produtos por unidade de medida, tal como por quilo, por litro, por metro ou por outra unidade, conforme o caso.</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> A informação de que trata o inciso III do caput deste artigo deve ser acessível à pessoa com deficiência, observado o disposto em regulamento. \<span class="cl-oab-badge">Caiu OAB 29</span>*</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 7° CDC.</strong> <span class="cl-art-texto">Os direitos previstos neste código não excluem outros decorrentes de tratados ou convenções internacionais de que o Brasil seja signatário, da legislação interna ordinária, de regulamentos expedidos pelas autoridades administrativas competentes, bem como dos que derivem dos princípios gerais do direito, analogia, costumes e eqüidade.</span></div>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Tendo mais de um autor a ofensa, todos responderão solidariamente pela reparação dos danos previstos nas normas de consumo. \<span class="cl-oab-badge">Caiu OAB 31</span>*</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 8 CDC.</strong> <span class="cl-art-texto">Os produtos e serviços colocados no mercado de consumo não acarretarão riscos à saúde ou segurança dos consumidores, exceto os considerados normais e previsíveis em decorrência de sua natureza e fruição, obrigando-se os fornecedores, em qualquer hipótese, a dar as informações necessárias e adequadas a seu respeito. \<span class="cl-oab-badge">Caiu OAB 28</span>*</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> Em se tratando de produto industrial, ao fabricante cabe prestar as informações a que se refere este artigo, através de impressos apropriados que devam acompanhar o produto.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> O fornecedor deverá higienizar os equipamentos e utensílios utilizados no fornecimento de produtos ou serviços, ou colocados à disposição do consumidor, e informar, de maneira ostensiva e adequada, quando for o caso, sobre o risco de contaminação.</p>
<p class="cl-texto">(CONSUMIDOR POR EQUIPARAÇÃO) Art. 17 CDC. Para os efeitos desta Seção, equiparam-se aos consumidores todas as vítimas do evento.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 24 CDC.</strong> <span class="cl-art-texto">A garantia legal de adequação do produto ou serviço independe de termo expresso, vedada a exoneração contratual do fornecedor.</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 49 CDC.</strong> <span class="cl-art-texto">O consumidor pode desistir do contrato, no prazo de 7 dias a contar de sua assinatura ou do ato de recebimento do produto ou serviço, sempre que a contratação de fornecimento de produtos e serviços ocorrer fora do estabelecimento comercial, especialmente por telefone ou a domicílio.\<span class="cl-oab-badge">Caiu OAB 42</span>*</span></div>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Se o consumidor exercitar o direito de arrependimento previsto neste artigo, os valores eventualmente pagos, a qualquer título, durante o prazo de reflexão, ser</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 81 CDC.</strong> <span class="cl-art-texto">A defesa dos interesses e direitos dos consumidores e das vítimas poderá ser exercida em juízo individualmente, ou a título coletivo. \<span class="cl-oab-badge">Caiu OAB 26</span>*</span></div>
<p class="cl-texto">(AÇÃO COLETIVA) Parágrafo único. A defesa coletiva será exercida quando se tratar de:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>interesses ou direitos difusos, assim entendidos, para efeitos deste código, os transindividuais, de natureza indivisível, de que sejam titulares pessoas indeterminadas e ligadas por circunstâncias de fato; (DIREITOS DIFUSOS)</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>interesses ou direitos coletivos, assim entendidos, para efeitos deste código, os transindividuais, de natureza indivisível de que seja titular grupo, categoria ou classe de pessoas ligadas entre si ou com a parte contrária por uma relação jurídica base; (DIREITOS COLETIVOS)</p>
<p class="cl-texto">III - interesses ou direitos individuais homogêneos, assim entendidos os decorrentes de origem comum. (DIREITOS INDIVIDUAIS HOMOGÊNEOS) \<span class="cl-oab-badge">Caiu OAB 33</span>* \<span class="cl-oab-badge">Caiu OAB 30</span>* \<span class="cl-oab-badge">Caiu OAB 27</span>*</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 82 CDC.</strong> <span class="cl-art-texto">Para os fins do art. 81, parágrafo único, são legitimados concorrentemente:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>o Ministério Público;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a União, os Estados, os Municípios e o Distrito Federal;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>as entidades e órgãos da Administração Pública, direta ou indireta, ainda que sem personalidade jurídica, especificamente destinados à defesa dos interesses e direitos protegidos por este código;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>as associações legalmente constituídas há pelo menos um ano e que incluam entre seus fins institucionais a defesa dos interesses e direitos protegidos por este código, dispensada a autorização assemblear.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> O requisito da pré-constituição pode ser dispensado pelo juiz, nas ações previstas nos arts. 91 e seguintes, quando haja manifesto interesse social evidenciado pela dimensão ou característica do dano, ou pela relevância do bem jurídico a ser protegido.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 88 CDC.</strong> <span class="cl-art-texto">Na hipótese do art. 13, parágrafo único deste código, a ação de regresso poderá ser ajuizada em processo autônomo, facultada a possibilidade de prosseguir-se nos mesmos autos, vedada a denunciação da lide. \<span class="cl-oab-badge">Caiu OAB 32</span>*</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 97 CDC.</strong> <span class="cl-art-texto">A liquidação e a execução de sentença poderão ser promovidas pela vítima e seus sucessores, assim como pelos legitimados de que trata o art. 82. \<span class="cl-oab-badge">Caiu OAB 30</span>* \<span class="cl-oab-badge">Caiu OAB 27</span>*</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 98 CDC.</strong> <span class="cl-art-texto">A execução poderá ser coletiva, sendo promovida pelos legitimados de que trata o art. 82, abrangendo as vítimas cujas indenizações já tiveram sido fixadas em sentença de liquidação, sem prejuízo do ajuizamento de outras execuções. \<span class="cl-oab-badge">Caiu OAB 27</span>*</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> A execução coletiva far-se-á com base em certidão das sentenças de liquidação, da qual deverá constar a ocorrência ou não do trânsito em julgado.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> É competente para a execução o juízo:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>da liquidação da sentença ou da ação condenatória, no caso de execução individual;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>da ação condenatória, quando coletiva a execução.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 396 CPC.</strong> <span class="cl-art-texto">O juiz pode ordenar que a parte exiba documento ou coisa que se encontre em seu poder.</span></div>
<h3 class="cl-section">RESPONSABILIDADE CIVIL DE RELAÇÕES DE CONSUMO</h3>
<div class="cl-artigo"><strong class="cl-art-num">Art. 8 CDC.</strong> <span class="cl-art-texto">Os produtos e serviços colocados no mercado de consumo não acarretarão riscos à saúde ou segurança dos consumidores, exceto os considerados normais e previsíveis em decorrência de sua natureza e fruição, obrigando-se os fornecedores, em qualquer hipótese, a dar as informações necessárias e adequadas a seu respeito. \<span class="cl-oab-badge">Caiu OAB 28</span>*</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> Em se tratando de produto industrial, ao fabricante cabe prestar as informações a que se refere este artigo, através de impressos apropriados que devam acompanhar o produto.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> O fornecedor deverá higienizar os equipamentos e utensílios utilizados no fornecimento de produtos ou serviços, ou colocados à disposição do consumidor, e informar, de maneira ostensiva e adequada, quando for o caso, sobre o risco de contaminação.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 10 CDC.</strong> <span class="cl-art-texto">O fornecedor não poderá colocar no mercado de consumo produto ou serviço que sabe ou deveria saber apresentar alto grau de nocividade ou periculosidade à saúde ou segurança.</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> O fornecedor de produtos e serviços que, posteriormente à sua introdução no mercado de consumo, tiver conhecimento da periculosidade que apresentem, deverá comunicar o fato imediatamente às autoridades competentes e aos consumidores, mediante anúncios publicitários.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Os anúncios publicitários a que se refere o parágrafo anterior serão veiculados na imprensa, rádio e televisão, às expensas do fornecedor do produto ou serviço.</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> Sempre que tiverem conhecimento de periculosidade de produtos ou serviços à saúde ou segurança dos consumidores, a União, os Estados, o Distrito Federal e os Municípios deverão informá-los a respeito. \<span class="cl-oab-badge">Caiu OAB 42</span>*</p>
<p class="cl-texto">(RESPONSABILIDADE PELO FATO DO PRODUTO) Art. 12. CDC. O fabricante, o produtor, o construtor, nacional ou estrangeiro, e o importador respondem, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos decorrentes de projeto, fabricação, construção, montagem, fórmulas, manipulação, apresentação ou acondicionamento de seus produtos, bem como por informações insuficientes ou inadequadas sobre sua utilização e riscos. \<span class="cl-oab-badge">Caiu OAB 32</span>* \<span class="cl-oab-badge">Caiu OAB 29</span>* \<span class="cl-oab-badge">Caiu OAB 26</span>* \<span class="cl-oab-badge">Caiu OAB 38</span>*</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> O produto é defeituoso quando não oferece a segurança que dele legitimamente se espera, levando-se em consideração as circunstâncias relevantes, entre as quais:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>sua apresentação;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>o uso e os riscos que razoavelmente dele se esperam;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>a época em que foi colocado em circulação.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> O produto não é considerado defeituoso pelo fato de outro de melhor qualidade ter sido colocado no mercado.</p>
<p class="cl-texto">(CAUSAS EXCLUDENTES DE RESPONSABILIDADE) §3° O fabricante, o construtor, o produtor ou importador só não será responsabilizado quando provar: \<span class="cl-oab-badge">Caiu OAB 38</span>*</p>
<p class="cl-texto">I - que não colocou o produto no mercado;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>que, embora haja colocado o produto no mercado, o defeito inexiste;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>a culpa exclusiva do consumidor ou de terceiro.</p>
<p class="cl-texto">(RESPONSABILIDADE DO COMERCIANTE) Art. 13 CDC. O comerciante é igualmente responsável, nos termos do artigo anterior, quando:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>o fabricante, o construtor, o produtor ou o importador não puderem ser identificados;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>o produto for fornecido sem identificação clara do seu fabricante, produtor, construtor ou importador;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>não conservar adequadamente os produtos perecíveis.</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Aquele que efetivar o pagamento ao prejudicado poderá exercer o direito de regresso contra os demais responsáveis, segundo sua participação na causação do evento danoso.</p>
<p class="cl-texto">(RESPONSABILIDADE PELO FATO DO SERVIÇO) Art. 14 CDC. O fornecedor de serviços responde, independentemente da existência de culpa, pela reparação dos danos causados aos consumidores por defeitos relativos à prestação dos serviços, bem como por informações insuficientes ou inadequadas sobre sua fruição e riscos.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> O serviço é defeituoso quando não fornece a segurança que o consumidor dele pode esperar, levando-se em consideração as circunstâncias relevantes, entre as quais:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>o modo de seu fornecimento;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>o resultado e os riscos que razoavelmente dele se esperam;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>a época em que foi fornecido.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> O serviço não é considerado defeituoso pela adoção de novas técnicas.</p>
<p class="cl-texto">(CAUSAS EXCLUDENTES DE RESPONSABILIDADE) §3° O fornecedor de serviços só não será responsabilizado quando provar:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>que, tendo prestado o serviço, o defeito inexiste;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a culpa exclusiva do consumidor ou de terceiro. \<span class="cl-oab-badge">Caiu OAB 26</span>*</p>
<p class="cl-paragrafo"><strong>§ 4°</strong> A responsabilidade pessoal dos profissionais liberais será apurada mediante a verificação de culpa. (RESPONSABILIDADE SUBJETIVA DOS PROFISSIONAIS LIBERAIS).</p>
<p class="cl-texto">(CONSUMIDOR POR EQUIPARAÇÃO) Art. 17 CDC. Para os efeitos desta Seção, equiparam-se aos consumidores todas as vítimas do evento.</p>
<p class="cl-texto">(RESPONSABILIDADE PELO VÍCIO DO PRODUTO) Art. 18 CDC. Os fornecedores de produtos de consumo duráveis ou não duráveis respondem solidariamente pelos vícios de qualidade ou quantidade que os tornem impróprios ou inadequados ao consumo a que se destinam ou lhes diminuam o valor, assim como por aqueles decorrentes da disparidade, com a indicações constantes do recipiente, da embalagem, rotulagem ou mensagem publicitária, respeitadas as variações decorrentes de sua natureza, podendo o consumidor exigir a substituição das partes viciadas. \<span class="cl-oab-badge">Caiu OAB 30</span>*</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> Não sendo o vício sanado no prazo máximo de trinta dias, pode o consumidor exigir, alternativamente e à sua escolha;</p>
<p class="cl-texto">I - a substituição do produto por outro da mesma espécie, em perfeitas condições de uso;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a restituição imediata da quantia paga, monetariamente atualizada, sem prejuízo de eventuais perdas e danos;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>o abatimento proporcional do preço.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Poderão as partes convencionar a redução ou ampliação do prazo previsto no parágrafo anterior, não podendo ser inferior a sete nem superior a cento e oitenta dias. Nos contratos de adesão, a cláusula de prazo deverá ser convencionada em separado, por meio de manifestação expressa do consumidor.</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> O consumidor poderá fazer uso imediato das alternativas do § 1° deste artigo sempre que, em razão da extensão do vício, a substituição das partes viciadas puder comprometer a qualidade ou características do produto, diminuir-lhe o valor ou se tratar de produto essencial.</p>
<p class="cl-paragrafo"><strong>§ 4°</strong> Tendo o consumidor optado pela alternativa do inciso I do § 1° deste artigo, e não sendo possível a substituição do bem, poderá haver substituição por outro de espécie, marca ou modelo diversos, mediante complementação ou restituição de eventual diferença de preço, sem prejuízo do disposto nos incisos II e III do § 1° deste artigo.</p>
<p class="cl-paragrafo"><strong>§ 5°</strong> No caso de fornecimento de produtos in natura, será responsável perante o consumidor o fornecedor imediato, exceto quando identificado claramente seu produtor.</p>
<p class="cl-paragrafo"><strong>§ 6°</strong> São impróprios ao uso e consumo:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>os produtos cujos prazos de validade estejam vencidos;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>os produtos deteriorados, alterados, adulterados, avariados, falsificados, corrompidos, fraudados, nocivos à vida ou à saúde, perigosos ou, ainda, aqueles em desacordo com as normas regulamentares de fabricação, distribuição ou apresentação;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>os produtos que, por qualquer motivo, se revelem inadequados ao fim a que se destinam.</p>
<p class="cl-texto">(VÍCIO DE QUANTIDADE DO PRODUTO) Art. 19. CDC. Os fornecedores respondem solidariamente pelos vícios de quantidade do produto sempre que, respeitadas as variações decorrentes de sua natureza, seu conteúdo líquido for inferior às indicações constantes do recipiente, da embalagem, rotulagem ou de mensagem publicitária, podendo o consumidor exigir, alternativamente e à sua escolha:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>o abatimento proporcional do preço;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>complementação do peso ou medida;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>a substituição do produto por outro da mesma espécie, marca ou modelo, sem os aludidos vícios;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>a restituição imediata da quantia paga, monetariamente atualizada, sem prejuízo de eventuais perdas e danos.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> Aplica-se a este artigo o disposto no § 4° do artigo anterior.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> O fornecedor imediato (COMERCIANTE) será responsável quando fizer a pesagem ou a medição e o instrumento utilizado não estiver aferido segundo os padrões oficiais.</p>
<p class="cl-texto">(VÍCIO DE QUALIDADE DO SERVIÇO) Art. 20 CDC. O fornecedor de serviços responde pelos vícios de qualidade que os tornem impróprios ao consumo ou lhes diminuam o valor, assim como por</p>
<p class="cl-texto">aqueles decorrentes da disparidade com as indicações constantes da oferta ou mensagem publicitária, podendo o consumidor exigir, alternativamente e à sua escolha:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>a reexecução dos serviços, sem custo adicional e quando cabível;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a restituição imediata da quantia paga, monetariamente atualizada, sem prejuízo de eventuais perdas e danos;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>o abatimento proporcional do preço.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> A reexecução dos serviços poderá ser confiada a terceiros devidamente capacitados, por conta e risco do fornecedor.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> São impróprios os serviços que se mostrem inadequados para os fins que razoavelmente deles se esperam, bem como aqueles que não atendam as normas regulamentares de prestabilidade.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 22 CDC.</strong> <span class="cl-art-texto">Os órgãos públicos, por si ou suas empresas, concessionárias, permissionárias ou sob qualquer outra forma de empreendimento, são obrigados a fornecer serviços adequados, eficientes, seguros e, quanto aos essenciais, contínuos;</span></div>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Nos casos de descumprimento, total ou parcial, das obrigações referidas neste artigo, serão as pessoas jurídicas compelidas a cumpri-las e a reparar os danos causados, na forma prevista neste código. (RESPONSABILIDADE OBJETIVA) \<span class="cl-oab-badge">Caiu OAB 34</span>*</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 23. CDC.</strong> <span class="cl-art-texto">A ignorância do fornecedor sobre os vícios de qualidade por inadequação dos produtos e serviços não o exime de responsabilidade.</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 25 CDC.</strong> <span class="cl-art-texto">É vedada a estipulação contratual de cláusula que impossibilite, exonere ou atenue a obrigação de indenizar prevista nesta e nas seções anteriores.</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> Havendo mais de um responsável pela causação do dano, todos responderão solidariamente pela reparação prevista nesta e nas seções anteriores. \<span class="cl-oab-badge">Caiu OAB 36</span>* \<span class="cl-oab-badge">Caiu OAB 25</span>*</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Sendo o dano causado por componente ou peça incorporada ao produto ou serviço, são responsáveis solidários seu fabricante, construtor ou importador e o que realizou a incorporação.</p>
<p class="cl-texto">(PRAZO DECADENCIAL) Art. 26 CDC. O direito de reclamar pelos vícios aparentes ou de fácil constatação caduca em:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>trinta dias, tratando-se de fornecimento de serviço e de produtos não duráveis; (SERVIÇO E PRODUTOS NÃO DURÁVEIS)</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>noventa dias, tratando-se de fornecimento de serviço e de produtos duráveis. (SERVIÇO E PRODUTOS DURÁVEIS)</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> Inicia-se a contagem do prazo decadencial a partir da entrega efetiva do produto ou do término da execução dos serviços.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Obstam a decadência:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>a reclamação comprovadamente formulada pelo consumidor perante o fornecedor de produtos e serviços até a resposta negativa correspondente, que deve ser transmitida de forma inequívoca; \<span class="cl-oab-badge">Caiu OAB 41</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>(Vetado).</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>a instauração de inquérito civil, até seu encerramento.</p>
<p class="cl-texto">§3° Tratando-se de vício oculto, o prazo decadencial inicia-se no momento em que ficar evidenciado o defeito. \<span class="cl-oab-badge">Caiu OAB 35</span>*</p>
<p class="cl-texto">(PRAZO PRESCRICIONAL) Art. 27 CDC. Prescreve em cinco anos a pretensão à reparação pelos danos causados por fato do produto ou do serviço prevista na Seção II deste Capítulo, iniciando-se a contagem do prazo a partir do conhecimento do dano e de sua autoria.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 28 CDC.</strong> <span class="cl-art-texto">O juiz poderá desconsiderar a personalidade jurídica da sociedade quando, em detrimento do consumidor, houver abuso de direito, excesso de poder, infração da lei, fato ou ato ilícito ou violação dos estatutos ou contrato social. A desconsideração também será efetivada quando houver falência, estado de insolvência, encerramento ou inatividade da pessoa jurídica provocados por má administração. (TEORIA MENOR DA DESCONSIDERAÇÃO DA PERSONALIDADE JURÍDICA)</span></div>
<p class="cl-paragrafo"><strong>§ 2°</strong> As sociedades integrantes dos grupos societários e as sociedades controladas, são subsidiariamente responsáveis pelas obrigações decorrentes deste código.</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> As sociedades consorciadas são solidariamente responsáveis pelas obrigações decorrentes deste código. \<span class="cl-oab-badge">Caiu OAB 36</span>*</p>
<p class="cl-paragrafo"><strong>§ 4°</strong> As sociedades coligadas só responderão por culpa.</p>
<p class="cl-paragrafo"><strong>§ 5°</strong> Também poderá ser desconsiderada a pessoa jurídica sempre que sua personalidade for, de alguma forma, obstáculo ao ressarcimento de prejuízos causados aos consumidores.</p>
<h2 class="cl-part">PROTEÇÃO CONTRATUAL</h2>
<p class="cl-texto">(DIREITO DE ARREPENDIMENTO) Art. 49 CDC. O consumidor pode desistir do contrato, no prazo de 7 dias a contar de sua assinatura ou do ato de recebimento do produto ou serviço, sempre que a contratação de fornecimento de produtos e serviços ocorrer fora do estabelecimento comercial, especialmente por telefone ou a domicílio. \<span class="cl-oab-badge">Caiu OAB 36</span>* \<span class="cl-oab-badge">Caiu OAB 41</span>*</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Se o consumidor exercitar o direito de arrependimento previsto neste artigo, os valores eventualmente pagos, a qualquer título, durante o prazo de reflexão, serão devolvidos, de imediato, monetariamente atualizados.</p>
<p class="cl-texto">(CLÁUSULAS ABUSIVAS) Art. 51 CDC. São nulas de pleno direito, entre outras, as cláusulas contratuais relativas ao fornecimento de produtos e serviços que:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>impossibilitem, exonerem ou atenuem a responsabilidade do fornecedor por vícios de qualquer natureza dos produtos e serviços ou impliquem renúncia ou disposição de direitos. Nas relações de consumo entre o fornecedor e o consumidor pessoa jurídica, a indenização poderá ser limitada, em situações justificáveis; \<span class="cl-oab-badge">Caiu OAB 34</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>subtraiam ao consumidor a opção de reembolso da quantia já paga, nos casos previstos neste código;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>transfiram responsabilidades a terceiros;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>estabeleçam obrigações consideradas iníquas, abusivas, que coloquem o consumidor em desvantagem exagerada, ou sejam incompatíveis com a boa-fé ou a eqüidade;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>(Vetado);</p>
<p class="cl-inciso"><span class="cl-inc-num">VI –</span>estabeleçam inversão do ônus da prova em prejuízo do consumidor;</p>
<p class="cl-inciso"><span class="cl-inc-num">VII –</span>determinem a utilização compulsória de arbitragem;</p>
<p class="cl-inciso"><span class="cl-inc-num">VIII –</span>imponham representante para concluir ou realizar outro negócio jurídico pelo consumidor;</p>
<p class="cl-inciso"><span class="cl-inc-num">IX –</span>deixem ao fornecedor a opção de concluir ou não o contrato, embora obrigando o consumidor;</p>
<p class="cl-inciso"><span class="cl-inc-num">X –</span>permitam ao fornecedor, direta ou indiretamente, variação do preço de maneira unilateral;</p>
<p class="cl-inciso"><span class="cl-inc-num">XI –</span>autorizem o fornecedor a cancelar o contrato unilateralmente, sem que igual direito seja conferido ao consumidor;</p>
<p class="cl-inciso"><span class="cl-inc-num">XII –</span>obriguem o consumidor a ressarcir os custos de cobrança de sua obrigação, sem que igual direito lhe seja conferido contra o fornecedor;</p>
<p class="cl-inciso"><span class="cl-inc-num">XIII –</span>autorizem o fornecedor a modificar unilateralmente o conteúdo ou a qualidade do contrato, após sua celebração;</p>
<p class="cl-inciso"><span class="cl-inc-num">XIV –</span>infrinjam ou possibilitem a violação de normas ambientais;</p>
<p class="cl-inciso"><span class="cl-inc-num">XV –</span>estejam em desacordo com o sistema de proteção ao consumidor;</p>
<p class="cl-inciso"><span class="cl-inc-num">XVI –</span>possibilitem a renúncia do direito de indenização por benfeitorias necessárias.</p>
<p class="cl-inciso"><span class="cl-inc-num">XVII –</span>condicionem ou limitem de qualquer forma o acesso aos órgãos do Poder Judiciário;</p>
<p class="cl-texto">XVIII - estabeleçam prazos de carência em caso de impontualidade das prestações mensais ou impeçam o restabelecimento integral dos direitos do consumidor e de seus meios de pagamento a partir da purgação da mora ou do acordo com os credores;</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> Presume-se exagerada, entre outros casos, a vantagem que:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>ofende os princípios fundamentais do sistema jurídico a que pertence;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>restringe direitos ou obrigações fundamentais inerentes à natureza do contrato, de tal modo a ameaçar seu objeto ou equilíbrio contratual;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>se mostra excessivamente onerosa para o consumidor, considerando-se a natureza e conteúdo do contrato, o interesse das partes e outras circunstâncias peculiares ao caso.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> A nulidade de uma cláusula contratual abusiva não invalida o contrato, exceto quando de sua ausência, apesar dos esforços de integração, decorrer ônus excessivo a qualquer das partes. \<span class="cl-oab-badge">Caiu OAB 26</span>*</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> (Vetado).</p>
<p class="cl-paragrafo"><strong>§ 4°</strong> É facultado a qualquer consumidor ou entidade que o represente requerer ao Ministério Público que ajuíze a competente ação para ser declarada a nulidade de cláusula contratual que contrarie o disposto neste código ou de qualquer forma não assegure o justo equilíbrio entre direitos e obrigações das partes.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 52 CDC.</strong> <span class="cl-art-texto">No fornecimento de produtos ou serviços que envolva outorga de crédito ou concessão de financiamento ao consumidor, o fornecedor deverá, entre outros requisitos, informá-lo prévia e adequadamente sobre:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>preço do produto ou serviço em moeda corrente nacional;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>montante dos juros de mora e da taxa efetiva anual de juros;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>acréscimos legalmente previstos;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>número e periodicidade das prestações;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>soma total a pagar, com e sem financiamento.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> As multas de mora decorrentes do inadimplemento de obrigações no seu termo não poderão ser superiores a dois por cento do valor da prestação.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> É assegurado ao consumidor a liquidação antecipada do débito, total ou parcialmente, mediante redução proporcional dos juros e demais acréscimos.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 54</strong> <span class="cl-art-texto">-A CDC. Este Capítulo dispõe sobre a prevenção do superendividamento da pessoa natural, sobre o crédito responsável e sobre a educação financeira do consumidor. (Incluído pela Lei nº 14.181, de 2021):</span></div>
<p class="cl-texto">(CONCEITO DE SUPERENDIVIDAMENTO) §1º Entende-se por superendividamento a impossibilidade manifesta de o consumidor pessoa natural, de boa-fé, pagar a totalidade de suas dívidas de consumo, exigíveis e vincendas, sem comprometer seu mínimo existencial, nos termos da regulamentação.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> As dívidas referidas no § 1º deste artigo englobam quaisquer compromissos financeiros assumidos decorrentes de relação de consumo, inclusive operações de crédito, compras a prazo e serviços de prestação continuada.</p>
<p class="cl-texto">§3º O disposto neste Capítulo não se aplica ao consumidor cujas dívidas tenham sido contraídas mediante fraude ou má-fé, sejam oriundas de contratos celebrados dolosamente com o propósito de não realizar o pagamento ou decorram da aquisição ou contratação de produtos e serviços de luxo de alto valor.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 54</strong> <span class="cl-art-texto">-B CDC. No fornecimento de crédito e na venda a prazo, além das informações obrigatórias previstas no art. 52 deste Código e na legislação aplicável à matéria, o fornecedor ou o intermediário deverá informar o consumidor, prévia e adequadamente, no momento da oferta, sobre (Incluído pela Lei nº 14.181, de 2021): \<span class="cl-oab-badge">Caiu OAB 37</span>*</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>o custo efetivo total e a descrição dos elementos que o compõem;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a taxa efetiva mensal de juros, bem como a taxa dos juros de mora e o total de encargos, de qualquer natureza, previstos para o atraso no pagamento;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>o montante das prestações e o prazo de validade da oferta, que deve ser, no mínimo, de 2 (dois) dias; \<span class="cl-oab-badge">Caiu OAB 37</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>o nome e o endereço, inclusive o eletrônico, do fornecedor;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>o direito do consumidor à liquidação antecipada e não onerosa do débito, nos termos do §2º do art. 52 deste Código e da regulamentação em vigor.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> As informações referidas no art. 52 deste Código e no caput deste artigo devem constar de forma clara e resumida do próprio contrato, da fatura ou de instrumento apartado, de fácil acesso ao consumidor. \<span class="cl-oab-badge">Caiu OAB 37</span>*</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Para efeitos deste Código, o custo efetivo total da operação de crédito ao consumidor consistirá em taxa percentual anual e compreenderá todos os valores cobrados do consumidor, sem prejuízo do cálculo padronizado pela autoridade reguladora do sistema financeiro.</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> Sem prejuízo do disposto no art. 37 deste Código, a oferta de crédito ao consumidor e a oferta de venda a prazo, ou a fatura mensal, conforme o caso, devem indicar, no mínimo, o custo efetivo total, o agente financiador e a soma total a pagar, com e sem financiamento.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 54</strong> <span class="cl-art-texto">-C CDC. É vedado, expressa ou implicitamente, na oferta de crédito ao consumidor, publicitária ou não:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>(VETADO);</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>indicar que a operação de crédito poderá ser concluída sem consulta a serviços de proteção ao crédito ou sem avaliação da situação financeira do consumidor; \<span class="cl-oab-badge">Caiu OAB 41</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>ocultar ou dificultar a compreensão sobre os ônus e os riscos da contratação do crédito ou da venda a prazo;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>assediar ou pressionar o consumidor para contratar o fornecimento de produto, serviço ou crédito, principalmente se se tratar de consumidor idoso, analfabeto, doente ou em estado de vulnerabilidade agravada ou se a contratação envolver prêmio;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>condicionar o atendimento de pretensões do consumidor ou o início de tratativas à renúncia ou à desistência de demandas judiciais, ao pagamento de honorários advocatícios ou a depósitos judiciais.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 54</strong> <span class="cl-art-texto">-D CDC. Na oferta de crédito, previamente à contratação, o fornecedor ou o intermediário deverá, entre outras condutas:</span></div>
<p class="cl-texto">I - informar e esclarecer adequadamente o consumidor, considerada sua idade, sobre a natureza e a modalidade do crédito oferecido, sobre todos os custos incidentes, observado o disposto nos arts. 52 e 54-B deste Código, e sobre as consequências genéricas e específicas do inadimplemento;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>avaliar, de forma responsável, as condições de crédito do consumidor, mediante análise das informações disponíveis em bancos de dados de proteção ao crédito, observado o disposto neste Código e na legislação sobre proteção de dados; \<span class="cl-oab-badge">Caiu OAB 41</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>informar a identidade do agente financiador e entregar ao consumidor, ao garante e a outros coobrigados cópia do contrato de crédito.</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> O descumprimento de qualquer dos deveres previstos no caput deste artigo e nos arts. 52 e 54-C deste Código poderá acarretar judicialmente a redução dos juros, dos encargos ou de qualquer acréscimo ao principal e a dilação do prazo de pagamento previsto no contrato original, conforme a gravidade da conduta do fornecedor e as possibilidades financeiras do consumidor, sem prejuízo de outras sanções e de indenização por perdas e danos, patrimoniais e morais, ao consumidor.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 12.</strong> <span class="cl-art-texto">LEI 9.656/98. São facultadas a oferta, a contratação e a vigência dos produtos de que tratam o inciso I e o § 1o do art. 1o desta Lei, nas segmentações previstas nos incisos I a IV deste artigo, respeitadas as respectivas amplitudes de cobertura definidas no plano-referência de que trata o art. 10, segundo as seguintes exigências mínimas:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>quando incluir atendimento ambulatorial:</p>
<p class="cl-alinea">a) cobertura de consultas médicas, em número ilimitado, em clínicas básicas e especializadas, reconhecidas pelo Conselho Federal de Medicina;</p>
<p class="cl-alinea">b) cobertura de serviços de apoio diagnóstico, tratamentos e demais procedimentos ambulatoriais, solicitados pelo médico assistente;</p>
<p class="cl-alinea">c) cobertura de tratamentos antineoplásicos domiciliares de uso oral, incluindo medicamentos para o controle de efeitos adversos relacionados ao tratamento e adjuvantes;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>quando incluir internação hospitalar:</p>
<p class="cl-alinea">a) cobertura de internações hospitalares, vedada a limitação de prazo, valor máximo e quantidade, em clínicas básicas e especializadas, reconhecidas pelo Conselho Federal de Medicina, admitindo-se a exclusão dos procedimentos obstétricos;</p>
<p class="cl-alinea">b) cobertura de internações hospitalares em centro de terapia intensiva, ou similar, vedada a limitação de prazo, valor máximo e quantidade, a critério do médico assistente;</p>
<p class="cl-alinea">c) cobertura de despesas referentes a honorários médicos, serviços gerais de enfermagem e alimentação;</p>
<p class="cl-alinea">d) cobertura de exames complementares indispensáveis para o controle da evolução da doença e elucidação diagnóstica, fornecimento de medicamentos, anestésicos, gases medicinais, transfusões e sessões de quimioterapia e radioterapia, conforme prescrição do médico assistente, realizados ou ministrados durante o período de internação hospitalar;</p>
<p class="cl-alinea">e) cobertura de toda e qualquer taxa, incluindo materiais utilizados, assim como da remoção do paciente, comprovadamente necessária, para outro estabelecimento hospitalar, dentro dos limites de abrangência geográfica previstos no contrato, em território brasileiro; e</p>
<p class="cl-texto">f) cobertura de despesas de acompanhante, no caso de pacientes menores de dezoito anos;</p>
<p class="cl-alinea">g) cobertura para tratamentos antineoplásicos ambulatoriais e domiciliares de uso oral, procedimentos radioterápicos para tratamento de câncer e hemoterapia, na qualidade de procedimentos cuja necessidade esteja relacionada à continuidade da assistência prestada em âmbito de internação hospitalar;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>quando incluir atendimento obstétrico:</p>
<p class="cl-alinea">a) cobertura assistencial ao recém-nascido, filho natural ou adotivo do consumidor, ou de seu dependente, durante os primeiros trinta dias após o parto;</p>
<p class="cl-alinea">b) inscrição assegurada ao recém-nascido, filho natural ou adotivo do consumidor, como dependente, isento do cumprimento dos períodos de carência, desde que a inscrição ocorra no prazo máximo de trinta dias do nascimento ou da adoção;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>quando incluir atendimento odontológico:</p>
<p class="cl-alinea">a) cobertura de consultas e exames auxiliares ou complementares, solicitados pelo odontólogo assistente;</p>
<p class="cl-alinea">b) cobertura de procedimentos preventivos, de dentística e endodontia;</p>
<p class="cl-alinea">c) cobertura de cirurgias orais menores, assim consideradas as realizadas em ambiente ambulatorial e sem anestesia geral;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>quando fixar períodos de carência: \<span class="cl-oab-badge">Caiu OAB 27</span>*</p>
<p class="cl-alinea">a) prazo máximo de trezentos dias para partos a termo;</p>
<p class="cl-alinea">b) prazo máximo de cento e oitenta dias para os demais casos;</p>
<p class="cl-alinea">c) prazo máximo de vinte e quatro horas para a cobertura dos casos de urgência e emergência; \<span class="cl-oab-badge">Caiu OAB 27</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">VI –</span>reembolso, em todos os tipos de produtos de que tratam o inciso I e o § 1o do art. 1o desta Lei, nos limites das obrigações contratuais, das despesas efetuadas pelo beneficiáriocom assistência à saúde, em casos de urgência ou emergência, quando não for possível a utilização dos serviços próprios, contratados, credenciados ou referenciados pelas operadoras, de acordo com a relação de preços de serviços médicos e hospitalares praticados pelo respectivo produto, pagáveis no prazo máximo de trinta dias após a entrega da documentação adequada;</p>
<p class="cl-inciso"><span class="cl-inc-num">VII –</span>inscrição de filho adotivo, menor de doze anos de idade, aproveitando os períodos de carência já cumpridos pelo consumidor adotante.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 31</strong> <span class="cl-art-texto">LEI 9.656/98. Ao aposentado que contribuir para produtos de que tratam o inciso I e o § 1o do art. 1o desta Lei, em decorrência de vínculo empregatício, pelo prazo mínimo de dez anos, é assegurado o direito de manutenção como beneficiário, nas mesmas condições de cobertura assistencial de que gozava quando da vigência do contrato de trabalho, desde que assuma o seu pagamento integral. \<span class="cl-oab-badge">Caiu OAB 32</span>*</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 35</strong> <span class="cl-art-texto">-F LEI 9.656/98. A assistência a que alude o art. 1o desta Lei compreende todas as ações necessárias à prevenção da doença e à recuperação, manutenção e reabilitação da saúde, observados os termos desta Lei e do contrato firmado entre as partes. \<span class="cl-oab-badge">Caiu OAB 31</span>*</span></div>
<p class="cl-texto">SÚMULA 302 STJ - É abusiva a cláusula contratual de plano de saúde que limita no tempo a internação hospitalar do segurado. \<span class="cl-oab-badge">Caiu OAB 38</span>*</p>
<p class="cl-texto">SÚMULA 597 STJ - A cláusula contratual de plano de saúde que prevê carência para utilização dos serviços de assistência médica nas situações de emergência ou de urgência é considerada abusiva se ultrapassado o prazo máximo de 24 horas contado da data da contratação. \<span class="cl-oab-badge">Caiu OAB 27</span>*</p>
<p class="cl-texto">SÚMULA 638 STJ - É abusiva a cláusula contratual que restringe a responsabilidade de instituição financeira pelos danos decorrentes de roubo, furto ou extravio de bem entregue em garantia no âmbito de contrato de penhor civil. \<span class="cl-oab-badge">Caiu OAB 34</span>*</p>
<h2 class="cl-part">PRÁTICAS COMERCIAIS</h2>
<div class="cl-artigo"><strong class="cl-art-num">Art. 29 CDC.</strong> <span class="cl-art-texto">Para os fins deste Capítulo e do seguinte, equiparam-se aos consumidores todas as pessoas determináveis ou não, expostas às práticas nele previstas.</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 30 CDC.</strong> <span class="cl-art-texto">Toda informação ou publicidade, suficientemente precisa, veiculada por qualquer forma ou meio de comunicação com relação a produtos e serviços oferecidos ou apresentados, obriga o fornecedor que a fizer veicular ou dela se utilizar e integra o contrato que vier a ser celebrado.</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 31 CDC.</strong> <span class="cl-art-texto">A oferta e apresentação de produtos ou serviços devem assegurar informações corretas, claras, precisas, ostensivas e em língua portuguesa sobre suas características, qualidades, quantidade, composição, preço, garantia, prazos de validade e origem, entre outros dados, bem como sobre os riscos que apresentam à saúde e segurança dos consumidores. \<span class="cl-oab-badge">Caiu OAB 28</span>*</span></div>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> As informações de que trata este artigo, nos produtos refrigerados oferecidos ao consumidor, serão gravadas de forma indelével.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 32 CDC.</strong> <span class="cl-art-texto">Os fabricantes e importadores deverão assegurar a oferta de componentes e peças de reposição enquanto não cessar a fabricação ou importação do produto.</span></div>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Cessadas a produção ou importação, a oferta deverá ser mantida por período razoável de tempo, na forma da lei.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 34 CDC.</strong> <span class="cl-art-texto">O fornecedor do produto ou serviço é solidariamente responsável pelos atos de seus prepostos ou representantes autônomos. \<span class="cl-oab-badge">Caiu OAB 31</span>*</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 37 CDC.</strong> <span class="cl-art-texto">É proibida toda publicidade enganosa ou abusiva.</span></div>
<p class="cl-texto">(PUBLICIDADE ENGANOSA) §1° É enganosa qualquer modalidade de informação ou comunicação de caráter publicitário, inteira ou parcialmente falsa, ou, por qualquer outro modo, mesmo por omissão, capaz de induzir em erro o consumidor a respeito da natureza, características, qualidade, quantidade, propriedades, origem, preço e quaisquer outros dados sobre produtos e serviços. \<span class="cl-oab-badge">Caiu OAB 26</span>*</p>
<p class="cl-texto">(PUBLICIDADE ABUSIVA) §2° É abusiva, dentre outras a publicidade discriminatória de qualquer natureza, a que incite à violência, explore o medo ou a superstição, se aproveite da deficiência de julgamento e experiência da criança, desrespeita valores ambientais, ou que seja capaz de induzir o consumidor a se comportar de forma prejudicial ou perigosa à sua saúde ou segurança. \<span class="cl-oab-badge">Caiu OAB 33</span>*</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> Para os efeitos deste código, a publicidade é enganosa por omissão quando deixar de informar sobre dado essencial do produto ou serviço.</p>
<p class="cl-texto">(PRÁTICAS ABUSIVAS) Art. 39 CDC. É vedado ao fornecedor de produtos ou serviços, dentre outras práticas abusivas:</p>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>condicionar o fornecimento de produto ou de serviço ao fornecimento de outro produto ou serviço, bem como, sem justa causa, a limites quantitativos; (VENDA CASADA) \<span class="cl-oab-badge">Caiu OAB 37</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>recusar atendimento às demandas dos consumidores, na exata medida de suas disponibilidades de estoque, e, ainda, de conformidade com os usos e costumes;</p>
<p class="cl-texto">III - enviar ou entregar ao consumidor, sem solicitação prévia, qualquer produto, ou fornecer qualquer serviço;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>prevalecer-se da fraqueza ou ignorância do consumidor, tendo em vista sua idade, saúde, conhecimento ou condição social, para impingir-lhe seus produtos ou serviços;</p>
<p class="cl-inciso"><span class="cl-inc-num">V –</span>exigir do consumidor vantagem manifestamente excessiva;</p>
<p class="cl-inciso"><span class="cl-inc-num">VI –</span>executar serviços sem a prévia elaboração de orçamento e autorização expressa do consumidor, ressalvadas as decorrentes de práticas anteriores entre as partes;</p>
<p class="cl-inciso"><span class="cl-inc-num">VII –</span>repassar informação depreciativa, referente a ato praticado pelo consumidor no exercício de seus direitos;</p>
<p class="cl-inciso"><span class="cl-inc-num">VIII –</span>colocar, no mercado de consumo, qualquer produto ou serviço em desacordo com as normas expedidas pelos órgãos oficiais competentes ou, se normas específicas não existirem, pela Associação Brasileira de Normas Técnicas ou outra entidade credenciada pelo Conselho Nacional de Metrologia, Normalização e Qualidade Industrial (Conmetro);</p>
<p class="cl-inciso"><span class="cl-inc-num">IX –</span>recusar a venda de bens ou a prestação de serviços, diretamente a quem se disponha a adquiri-los mediante pronto pagamento, ressalvados os casos de intermediação regulados em leis especiais; \<span class="cl-oab-badge">Caiu OAB 33</span>*</p>
<p class="cl-inciso"><span class="cl-inc-num">X –</span>elevar sem justa causa o preço de produtos ou serviços.</p>
<p class="cl-inciso"><span class="cl-inc-num">XI –</span>Dispositivo incluído pela MPV nº 1.890-67, de 22.10.1999, transformado em inciso XIII, quando da conversão na Lei nº 9.870, de 23.11.1999</p>
<p class="cl-inciso"><span class="cl-inc-num">XII –</span>deixar de estipular prazo para o cumprimento de sua obrigação ou deixar a fixação de seu termo inicial a seu exclusivo critério.</p>
<p class="cl-inciso"><span class="cl-inc-num">XIII –</span>aplicar fórmula ou índice de reajuste diverso do legal ou contratualmente estabelecido.</p>
<p class="cl-inciso"><span class="cl-inc-num">XIV –</span>permitir o ingresso em estabelecimentos comerciais ou de serviços de um número maior de consumidores que o fixado pela autoridade administrativa como máximo.</p>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> Os serviços prestados e os produtos remetidos ou entregues ao consumidor, na hipótese prevista no inciso III, equiparam-se às amostras grátis, inexistindo obrigação de pagamento.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 40. CDC.</strong> <span class="cl-art-texto">O fornecedor de serviço será obrigado a entregar ao consumidor orçamento prévio discriminando o valor da mão-de-obra, dos materiais e equipamentos a serem empregados, as condições de pagamento, bem como as datas de início e término dos serviços.</span></div>
<p class="cl-paragrafo"><strong>§ 1°</strong> Salvo estipulação em contrário, o valor orçado terá validade pelo prazo de dez dias, contado de seu recebimento pelo consumidor.</p>
<p class="cl-paragrafo"><strong>§ 2°</strong> Uma vez aprovado pelo consumidor, o orçamento obriga os contraentes e somente pode ser alterado mediante livre negociação das partes.</p>
<p class="cl-paragrafo"><strong>§ 3°</strong> O consumidor não responde por quaisquer ônus ou acréscimos decorrentes da contratação de serviços de terceiros não previstos no orçamento prévio.</p>
<p class="cl-texto">(DIREITO DE ARREPENDIMENTO) Art. 49 CDC. O consumidor pode desistir do contrato, no prazo de 7 dias a contar de sua assinatura ou do ato de recebimento do produto ou serviço, sempre que a contratação de fornecimento de produtos e serviços ocorrer fora do estabelecimento comercial, especialmente por telefone ou a domicílio.</p>
<p class="cl-texto">Parágrafo único. Se o consumidor exercitar o direito de arrependimento previsto neste artigo, os valores eventualmente pagos, a qualquer título, durante o prazo de reflexão, serão devolvidos, de imediato, monetariamente atualizados.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 72 CDC.</strong> <span class="cl-art-texto">Impedir ou dificultar o acesso do consumidor às informações que sobre ele constem em cadastros, banco de dados, fichas e registros:</span></div>
<p class="cl-texto">Pena - Detenção de seis meses a um ano ou multa.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 1º</strong> <span class="cl-art-texto">LEI 12.436/11 - É vedado às empresas e pessoas físicas empregadoras ou tomadoras de serviços prestados por motociclistas estabelecer práticas que estimulem o aumento de velocidade, tais como:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>oferecer prêmios por cumprimento de metas por números de entregas ou prestação de serviço;</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>prometer dispensa de pagamento ao consumidor, no caso de fornecimento de produto ou prestação de serviço fora do prazo ofertado para a sua entrega ou realização;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>estabelecer competição entre motociclistas, com o objetivo de elevar o número de entregas ou de prestação de serviço.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 15</strong> <span class="cl-art-texto">LEI 10.741/03 - É assegurada a atenção integral à saúde da pessoa idosa, por intermédio do Sistema Único de Saúde (SUS), garantindo-lhe o acesso universal e igualitário, em conjunto articulado e contínuo das ações e serviços, para a prevenção, promoção, proteção e recuperação da saúde, incluindo a atenção especial às doenças que afetam preferencialmente as pessoas idosas.</span></div>
<p class="cl-paragrafo"><strong>§ 3°</strong> É vedada a discriminação da pessoa idosa nos planos de saúde pela cobrança de valores diferenciados em razão da idade. \<span class="cl-oab-badge">Caiu OAB 28</span>*</p>
<p class="cl-texto">SÚMULA 548 STJ: - Incumbe ao credor a exclusão do registro da dívida em nome do devedor no cadastro de inadimplentes no prazo de cinco dias úteis, a partir do integral e efetivo pagamento do débito.</p>
<p class="cl-texto">SÚMULA 532 STJ - Constitui prática comercial abusiva o envio de cartão de crédito sem prévia e expressa solicitação do consumidor, configurando-se ato ilícito indenizável e sujeito à aplicação de multa administrativa.</p>
<p class="cl-texto">Súmula 550 STJ – A utilização de escore de crédito, método estatístico de avaliação de risco que não constitui banco de dados, dispensa o consentimento do consumidor, que terá o direito de solicitar esclarecimentos sobre as informações pessoais valoradas e as fontes dos dados considerados no respectivo cálculo. \<span class="cl-oab-badge">Caiu OAB 39</span>*</p>
<h2 class="cl-part">DEFESA EM JUÍZO DO CONSUMIDOR</h2>
<div class="cl-artigo"><strong class="cl-art-num">Art. 81 CDC.</strong> <span class="cl-art-texto">A defesa dos interesses e direitos dos consumidores e das vítimas poderá ser exercida em juízo individualmente, ou a título coletivo.</span></div>
<p class="cl-paragrafo"><strong>Parágrafo único.</strong> A defesa coletiva será exercida quando se tratar de:</p>
<p class="cl-inciso"><span class="cl-inc-num">I – –</span>interesses ou direitos difusos, assim entendidos, para efeitos deste código, os transindividuais, de natureza indivisível, de que sejam titulares pessoas indeterminadas e ligadas por circunstâncias de fato;</p>
<p class="cl-inciso"><span class="cl-inc-num">II – –</span>interesses ou direitos coletivos, assim entendidos, para efeitos deste código, os transindividuais, de natureza indivisível de que seja titular grupo, categoria ou classe de pessoas ligadas entre si ou com a parte contrária por uma relação jurídica base;</p>
<p class="cl-inciso"><span class="cl-inc-num">III – –</span>interesses ou direitos individuais homogêneos, assim entendidos os decorrentes de origem comum. \<span class="cl-oab-badge">Caiu OAB 33</span>* \<span class="cl-oab-badge">Caiu OAB 27</span>*</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 82 CDC.</strong> <span class="cl-art-texto">Para os fins do art. 81, parágrafo único, são legitimados concorrentemente:</span></div>
<p class="cl-inciso"><span class="cl-inc-num">I –</span>o Ministério Público,</p>
<p class="cl-inciso"><span class="cl-inc-num">II –</span>a União, os Estados, os Municípios e o Distrito Federal;</p>
<p class="cl-inciso"><span class="cl-inc-num">III –</span>as entidades e órgãos da Administração Pública, direta ou indireta, ainda que sem personalidade jurídica, especificamente destinados à defesa dos interesses e direitos protegidos por este código;</p>
<p class="cl-inciso"><span class="cl-inc-num">IV –</span>as associações legalmente constituídas há pelo menos um ano e que incluam entre seus fins institucionais a defesa dos interesses e direitos protegidos por este código, dispensada a autorização assemblear.</p>
<p class="cl-paragrafo"><strong>§ 1°</strong> O requisito da pré-constituição pode ser dispensado pelo juiz, nas ações previstas nos arts. 91 e seguintes, quando haja manifesto interesse social evidenciado pela dimensão ou característica do dano, ou pela relevância do bem jurídico a ser protegido.</p>
<div class="cl-artigo"><strong class="cl-art-num">Art. 95 CDC.</strong> <span class="cl-art-texto">Em caso de procedência do pedido, a condenação será genérica, fixando a responsabilidade do réu pelos danos causados. \<span class="cl-oab-badge">Caiu OAB 29</span>*</span></div>
<div class="cl-artigo"><strong class="cl-art-num">Art. 97 CDC.</strong> <span class="cl-art-texto">A liquidação e a execução de sentença poderão ser promovidas pela vítima e seus sucessores, assim como pelos legitimados de que trata o art. 82. \<span class="cl-oab-badge">Caiu OAB 29</span>*</span></div>
<p class="cl-texto">[\\#3](#3)</p>
<p class="cl-texto">[\\#5](#5)</p>
<p class="cl-texto">[\\#8](#8)</p>
<p class="cl-texto">[\\#13](#13)</p>
<p class="cl-texto">[\\#19](#19)</p>
<p class="cl-texto">[\\#22](#22)</p>
<p class="cl-texto"><https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2021/Lei/L14181.htm#art1></p>
<p class="cl-texto"><https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2021/Lei/L14181.htm#art1></p>
<p class="cl-texto"><https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2021/Lei/L14181.htm#art1></p>
<p class="cl-texto"><https://www.planalto.gov.br/ccivil_03/_Ato2019-2022/2021/Lei/L14181.htm#art1></p>
</div>
`;
