// Flashcards · Direito Civil · Revisões 1, 2 e 3 do VDE (material em tabelas)
// Campos: ver fc-etica.js.
window.FC_VDE = (window.FC_VDE || []).concat([
  // ── Revisão 1 ──
  { id: 'civ-1-01', d: 'Direito Civil', r: 1, t: 'Pessoas naturais',
    f: 'Quem é absolutamente incapaz hoje? E relativamente?',
    v: 'Absolutamente: só o menor de 16 anos (representado). Relativamente (assistido): maiores de 16 e menores de 18, ébrios habituais, viciados em tóxicos, quem não pode exprimir vontade e pródigos.', b: 'arts. 3º e 4º CC' },
  { id: 'civ-1-02', d: 'Direito Civil', r: 1, t: 'Pessoas naturais',
    f: 'Tomada de decisão apoiada x curatela.',
    v: 'Apoiada: a pessoa com deficiência continua capaz e escolhe apoiadores de confiança; o contratante pode exigir que os apoiadores assinem. Curatela: depende de interdição judicial e nomeia curador para representar.', b: 'art. 1.783-A, § 5º, CC' },
  { id: 'civ-1-03', d: 'Direito Civil', r: 1, t: 'Pessoas naturais',
    f: 'Emancipação voluntária x judicial x legal.',
    v: 'Voluntária: pelos pais, por instrumento público, sem homologação, a partir de 16 anos. Judicial: pelo juiz, a pedido do tutor ou se os pais divergem, a partir de 16. Legal: casamento, emprego público efetivo, colação de grau, estabelecimento ou emprego com economia própria (16 anos).', b: null,
    p: 'O divórcio não desfaz a emancipação pelo casamento; os pais continuam respondendo solidariamente pelo ilícito do filho emancipado.' },
  { id: 'civ-1-04', d: 'Direito Civil', r: 1, t: 'Direitos da personalidade',
    f: 'Direito ao esquecimento é compatível com a CF?',
    v: 'Não, para o STF. Abusos na liberdade de expressão são tratados caso a caso, sem prejuízo de outras medidas.', b: null },
  { id: 'civ-1-05', d: 'Direito Civil', r: 1, t: 'Direitos da personalidade',
    f: 'Mudança de prenome após a maioridade e de pessoa trans.',
    v: 'Maior pode alterar o prenome pessoalmente, sem justificar. Pessoa trans altera prenome e sexo no registro sem decisão judicial ou administrativa.', b: null },
  { id: 'civ-1-06', d: 'Direito Civil', r: 1, t: 'Morte presumida',
    f: 'Morte presumida sem decretação de ausência: hipóteses.',
    v: 'Extremamente provável a morte de quem estava em perigo de vida, ou desaparecido em campanha ou prisioneiro não encontrado até 2 anos após a guerra. Só depois de esgotadas as buscas; a sentença fixa a data provável. Abre sucessão definitiva.', b: null },
  { id: 'civ-1-07', d: 'Direito Civil', r: 1, t: 'Comoriência',
    f: 'Cônjuges comorientes herdam um do outro?',
    v: 'Não são herdeiros entre si, mas mantêm a meação do regime de bens. Presume-se que morreram ao mesmo tempo quando não se sabe a ordem.', b: null },
  { id: 'civ-1-08', d: 'Direito Civil', r: 1, t: 'Pessoas jurídicas',
    f: 'Desconsideração: teoria maior x menor.',
    v: 'Maior (CC, art. 50): exige abuso — desvio de finalidade ou confusão patrimonial. Menor: basta a personalidade ser obstáculo ao ressarcimento, adotada no CDC e na lei ambiental.', b: 'art. 50 CC; art. 28, § 5º, CDC; art. 4º Lei 9.605/98', c: true,
    n: 'A tabela diz que a teoria menor é do "Código Civil", mas os artigos que ela cita são do CDC e da Lei 9.605/98.' },
  { id: 'civ-1-09', d: 'Direito Civil', r: 1, t: 'Pessoas jurídicas',
    f: 'Sócio que saiu há mais de 2 anos escapa da desconsideração?',
    v: 'Não. Para o STJ, a regra do art. 1.032 do CC não se aplica à desconsideração da personalidade jurídica.', b: 'art. 1.032 CC' },
  { id: 'civ-1-10', d: 'Direito Civil', r: 1, t: 'Pessoas jurídicas',
    f: 'Associação x fundação.',
    v: 'Associação: união de pessoas, sem fins econômicos, estatuto e registro. Fundação: patrimônio afetado a um fim de interesse público, criada por escritura pública ou testamento com dotação de bens.', b: null },
  { id: 'civ-1-11', d: 'Direito Civil', r: 1, t: 'Negócio jurídico',
    f: 'Condição suspensiva x resolutiva x termo x encargo.',
    v: 'Suspensiva ("se"): suspende aquisição e exercício, só há expectativa. Resolutiva ("enquanto"): há direito adquirido, que se extingue com o evento. Termo: evento futuro e certo; adia o exercício, não a aquisição. Encargo: não suspende aquisição nem exercício, salvo se previsto como condição suspensiva.', b: null },
  { id: 'civ-1-12', d: 'Direito Civil', r: 1, t: 'Negócio jurídico',
    f: 'Lesão x estado de perigo.',
    v: 'Lesão: premente necessidade ou inexperiência leva a prestação manifestamente desproporcional. Estado de perigo: assume obrigação excessiva para salvar a si ou alguém da família de grave dano conhecido pela outra parte. Ambos anuláveis.', b: null },
  { id: 'civ-1-13', d: 'Direito Civil', r: 1, t: 'Negócio jurídico',
    f: 'Simulação: nulo ou anulável?',
    v: 'Nulo. Subsiste o negócio dissimulado, se válido na substância e na forma.', b: null,
    p: 'É a exceção entre os defeitos: os vícios de consentimento e a fraude contra credores geram anulabilidade.' },
  { id: 'civ-1-14', d: 'Direito Civil', r: 1, t: 'Negócio jurídico',
    f: 'Compra e venda de imóvel acima de que valor exige escritura pública?',
    v: 'Acima de 30 vezes o maior salário mínimo vigente; sem escritura, o contrato é nulo.', b: 'art. 108 CC' },
  { id: 'civ-1-15', d: 'Direito Civil', r: 1, t: 'Negócio jurídico',
    f: 'Prazos para anular negócio jurídico.',
    v: 'Regra geral: 2 anos da conclusão. Erro, dolo, estado de perigo, lesão e fraude contra credores: 4 anos da celebração. Coação: 4 anos de quando cessar. Incapacidade relativa: 4 anos de quando cessar a incapacidade.', b: 'art. 179 CC (regra geral)' },
  { id: 'civ-1-16', d: 'Direito Civil', r: 1, t: 'Negócio jurídico',
    f: 'Nulidade absoluta x relativa: quem alega e quando.',
    v: 'Absoluta (nulo): qualquer interessado ou o juiz de ofício, a qualquer tempo, não se confirma. Relativa (anulável): só a parte prejudicada, nos prazos decadenciais; produz efeitos até ser anulado.', b: 'art. 177 CC' },
  { id: 'civ-1-17', d: 'Direito Civil', r: 1, t: 'Obrigações',
    f: 'Perecimento da coisa certa antes da tradição, com e sem culpa.',
    v: 'Sem culpa do devedor, a obrigação se resolve para as duas partes. Com culpa, ele responde pelo equivalente mais perdas e danos.', b: null,
    p: 'O devedor não pode substituir a coisa certa sem consentimento do credor (art. 234 CC).' },
  { id: 'civ-1-18', d: 'Direito Civil', r: 1, t: 'Obrigações',
    f: 'Coisa incerta: de quem é o risco antes da escolha?',
    v: 'Do devedor, até a concentração (escolha). Depois da escolha, passa ao credor. A escolha cabe ao devedor, salvo se o contrato der ao credor.', b: 'arts. 244 e 246 CC' },
  { id: 'civ-1-19', d: 'Direito Civil', r: 1, t: 'Obrigações',
    f: 'Obrigação alternativa: uma das prestações ficou impossível sem culpa.',
    v: 'A obrigação subsiste quanto à prestação que sobrou.', b: 'art. 255 CC' },
  { id: 'civ-1-20', d: 'Direito Civil', r: 1, t: 'Obrigações',
    f: 'Solidariedade passiva: a coisa pereceu por culpa de um devedor. Quem paga as perdas e danos?',
    v: 'Todos continuam solidários pelo equivalente, mas pelas perdas e danos só responde o culpado.', b: 'art. 279 CC' },
  { id: 'civ-1-21', d: 'Direito Civil', r: 1, t: 'Obrigações',
    f: 'Cessão de crédito com cláusula proibitiva: vale contra o cessionário?',
    v: 'Só se a proibição constar do instrumento da obrigação; não pode ser oposta ao cessionário de boa-fé se não constar.', b: null },
  { id: 'civ-1-22', d: 'Direito Civil', r: 1, t: 'Inadimplemento',
    f: 'Cláusula penal moratória x compensatória.',
    v: 'Moratória: para o atraso ou cláusula específica; é cumulativa com a obrigação principal. Compensatória: prefixa perdas e danos do inadimplemento total; o credor escolhe entre ela e o cumprimento (não cumula).', b: null },
  { id: 'civ-1-23', d: 'Direito Civil', r: 1, t: 'Inadimplemento',
    f: 'Arras confirmatórias x penitenciais.',
    v: 'Confirmatórias (presumidas no silêncio): indenização mínima, cabe indenização suplementar provando prejuízo maior. Penitenciais: dão direito de arrependimento; valem como indenização total, sem suplementar.', b: null,
    p: 'Quem deu as arras e desiste perde-as; quem recebeu e desiste devolve mais o equivalente.' },
  { id: 'civ-1-24', d: 'Direito Civil', r: 1, t: 'Adimplemento',
    f: 'Quando cabe pagamento em consignação?',
    v: 'Quando o devedor não sabe quem é o credor, o credor está ausente, não aceita receber ou não dá quitação. Pode consignar o devedor ou terceiro interessado.', b: null },
  { id: 'civ-1-25', d: 'Direito Civil', r: 1, t: 'Adimplemento',
    f: 'Imputação x dação em pagamento x confusão.',
    v: 'Imputação: o devedor escolhe qual de várias dívidas líquidas e vencidas com o mesmo credor está pagando. Dação: o credor aceita prestação diversa. Confusão: credor e devedor se tornam a mesma pessoa e a obrigação se extingue.', b: null },

  // ── Revisão 2 ──
  { id: 'civ-2-01', d: 'Direito Civil', r: 2, t: 'Contratos em geral',
    f: 'Contrato consensual x real. Exemplo de real.',
    v: 'Consensual se aperfeiçoa com o acordo de vontades (locação). Real exige a entrega da coisa (comodato).', b: null },
  { id: 'civ-2-02', d: 'Direito Civil', r: 2, t: 'Contratos em geral',
    f: 'Contrato atípico é permitido?',
    v: 'Sim, ficam na liberdade das partes, mesmo sem designação em lei.', b: 'art. 425 CC' },
  { id: 'civ-2-03', d: 'Direito Civil', r: 2, t: 'Contratos em geral',
    f: 'Exceção do contrato não cumprido.',
    v: 'Defesa pela qual uma parte suspende sua prestação enquanto a outra não cumprir a dela ou não der garantia de que cumprirá.', b: null },
  { id: 'civ-2-04', d: 'Direito Civil', r: 2, t: 'Contratos em geral',
    f: 'Estipulação em favor de terceiro x promessa de fato de terceiro.',
    v: 'Estipulação: as partes contratam um benefício para terceiro, que pode exigi-lo. Promessa de fato de terceiro: o promitente se obriga a fazer um terceiro cumprir algo e responde por perdas e danos se ele não cumprir.', b: null },
  { id: 'civ-2-05', d: 'Direito Civil', r: 2, t: 'Vício redibitório',
    f: 'Prazos da ação redibitória.',
    v: 'Móvel: 30 dias; imóvel: 1 ano, da entrega (se já tinha a posse, conta da alienação, pela metade). Vício que só aparece depois: 180 dias (móvel) ou 1 ano (imóvel) da descoberta.', b: 'art. 445 CC',
    p: 'Alienante que sabia do vício devolve o valor mais perdas e danos; se não sabia, só o valor e as despesas.' },
  { id: 'civ-2-06', d: 'Direito Civil', r: 2, t: 'Evicção',
    f: 'Evicção: requisitos e o que o evicto recebe.',
    v: 'Contrato oneroso, perda por ato judicial ou administrativo e direito do terceiro anterior. O evicto recebe o preço integral, os frutos que teve de restituir, despesas do contrato, prejuízos diretos, custas e honorários.', b: 'art. 450 CC' },
  { id: 'civ-2-07', d: 'Direito Civil', r: 2, t: 'Compra e venda',
    f: 'Venda de ascendente a descendente.',
    v: 'Anulável se não houver consentimento dos outros descendentes e do cônjuge do alienante.', b: null,
    p: 'Dispensa-se o consentimento do cônjuge casado na separação obrigatória.' },
  { id: 'civ-2-08', d: 'Direito Civil', r: 2, t: 'Doação',
    f: 'Doação universal e doação ao amante.',
    v: 'Doar todos os bens sem reservar o necessário à subsistência é nulo. Doação ao amante é anulável.', b: 'art. 548 CC' },
  { id: 'civ-2-09', d: 'Direito Civil', r: 2, t: 'Doação',
    f: 'Revogação da doação: hipóteses e prazo.',
    v: 'Ingratidão do donatário ou inexecução do encargo. Prazo de 1 ano do conhecimento do fato pelo doador.', b: null },
  { id: 'civ-2-10', d: 'Direito Civil', r: 2, t: 'Doação',
    f: 'Doação de pai a filho é o quê?',
    v: 'Adiantamento da herança: o bem deve ser trazido à colação no inventário.', b: null },
  { id: 'civ-2-11', d: 'Direito Civil', r: 2, t: 'Contratos em espécie',
    f: 'Mútuo x comodato.',
    v: 'Mútuo: bem fungível, empréstimo de consumo, transfere a propriedade (dinheiro). Comodato: bem infungível, empréstimo de uso, não transfere.', b: null },
  { id: 'civ-2-12', d: 'Direito Civil', r: 2, t: 'Fiança',
    f: 'Benefício de ordem do fiador: até quando e quando não cabe?',
    v: 'O fiador pode exigir, até a contestação, que primeiro se executem os bens do devedor. Não cabe se renunciou expressamente, se é principal pagador ou devedor solidário, ou se o devedor é insolvente ou falido.', b: null },
  { id: 'civ-2-13', d: 'Direito Civil', r: 2, t: 'Contratos em espécie',
    f: 'Empreitada: o empreiteiro fornece o quê?',
    v: 'Só mão de obra ou mão de obra e materiais. Não há subordinação ao dono da obra.', b: 'art. 610 CC' },
  { id: 'civ-2-14', d: 'Direito Civil', r: 2, t: 'Responsabilidade civil',
    f: 'Responsabilidade objetiva x subjetiva: elementos.',
    v: 'Objetiva: conduta, dano e nexo causal, sem culpa. Subjetiva: os mesmos mais culpa (negligência, imprudência ou imperícia) ou dolo.', b: null },
  { id: 'civ-2-15', d: 'Direito Civil', r: 2, t: 'Responsabilidade civil',
    f: 'Excludentes da responsabilidade civil.',
    v: 'Caso fortuito ou força maior, fato de terceiro e culpa exclusiva da vítima: rompem o nexo e afastam o dever de indenizar.', b: null },
  { id: 'civ-2-16', d: 'Direito Civil', r: 2, t: 'Responsabilidade civil',
    f: 'Excludentes de ilicitude no Código Civil.',
    v: 'Legítima defesa, exercício regular de direito, estrito cumprimento do dever legal e estado de necessidade.', b: null },
  { id: 'civ-2-17', d: 'Direito Civil', r: 2, t: 'Responsabilidade civil',
    f: 'Prescrição da reparação civil contratual x extracontratual.',
    v: 'Contratual: 10 anos. Extracontratual: 3 anos.', b: 'arts. 205 e 206 CC' },
  { id: 'civ-2-18', d: 'Direito Civil', r: 2, t: 'Responsabilidade civil',
    f: 'Lucro cessante x dano emergente x perda de uma chance.',
    v: 'Emergente: o que se perdeu diretamente. Lucro cessante: o ganho certo frustrado. Perda de uma chance: indeniza a oportunidade perdida, não o lucro.', b: null },

  // ── Revisão 3 ──
  { id: 'civ-3-01', d: 'Direito Civil', r: 3, t: 'Posse',
    f: 'Posse injusta pode ser defendida?',
    v: 'Sim, por ações possessórias contra terceiros, mas não contra quem perdeu a coisa para o possuidor. Posse injusta é a violenta, clandestina ou precária.', b: null },
  { id: 'civ-3-02', d: 'Direito Civil', r: 3, t: 'Posse',
    f: 'Interdito proibitório x manutenção x reintegração.',
    v: 'Interdito: ameaça. Manutenção: turbação (perturba sem tirar a posse). Reintegração: esbulho (perda da posse). Rito especial se a ação vier em até ano e dia; depois, rito comum.', b: null },
  { id: 'civ-3-03', d: 'Direito Civil', r: 3, t: 'Propriedade',
    f: 'Prazos da usucapião extraordinária e ordinária.',
    v: 'Extraordinária: 15 anos (reduz a 10), sem justo título nem boa-fé. Ordinária: 10 anos (reduz a 5), com justo título e boa-fé.', b: null },
  { id: 'civ-3-04', d: 'Direito Civil', r: 3, t: 'Propriedade',
    f: 'Usucapião especial urbana, rural e familiar.',
    v: 'Urbana: 5 anos, até 250 m², moradia, sem outro imóvel. Rural: 5 anos, até 50 ha, trabalho e moradia, sem outro imóvel. Familiar: 2 anos, até 250 m² urbanos, posse exclusiva após abandono do ex-cônjuge ou ex-companheiro.', b: null,
    p: 'Bem público não pode ser usucapido.' },
  { id: 'civ-3-05', d: 'Direito Civil', r: 3, t: 'Propriedade',
    f: 'Sanções à propriedade urbana que descumpre a função social.',
    v: 'Parcelamento ou edificação compulsórios, IPTU progressivo no tempo e desapropriação paga em títulos da dívida pública.', b: 'art. 182, § 2º, CF' },
  { id: 'civ-3-06', d: 'Direito Civil', r: 3, t: 'Família',
    f: 'Idade mínima para casar e casamento sem autorização dos pais.',
    v: 'Menor de 16 anos não casa em hipótese alguma. Entre 16 e 18, precisa de autorização dos pais (revogável até a celebração); sem ela, com suprimento judicial, o regime é o da separação obrigatória.', b: 'art. 1.518 CC (idade núbil)', c: true,
    n: 'A revisão atribui a proibição à "Lei 13.146/19"; conferir a lei que alterou o Código Civil.' },
  { id: 'civ-3-07', d: 'Direito Civil', r: 3, t: 'Família',
    f: 'Casamento nulo x anulável.',
    v: 'Nulo: infringe impedimento; qualquer interessado ou o MP pedem; não se confirma; ação imprescritível. Anulável: só quem se beneficia alega, não de ofício; admite confirmação; prazos decadenciais.', b: 'arts. 1.548 a 1.550 CC' },
  { id: 'civ-3-08', d: 'Direito Civil', r: 3, t: 'Família',
    f: 'Prazos para anular o casamento.',
    v: 'Incapaz de consentir: 180 dias. Mandato revogado: 180 dias. Menor de 16: 180 dias. Autoridade incompetente: 2 anos. Erro essencial: 3 anos. Coação: 4 anos.', b: null },
  { id: 'civ-3-09', d: 'Direito Civil', r: 3, t: 'Família',
    f: 'Causa impeditiva x suspensiva do casamento.',
    v: 'Impeditiva ("não podem casar"): ascendente com descendente, afins em linha reta, irmãos e colaterais até 3º grau, pessoas casadas, cônjuge sobrevivente com o condenado por homicídio do consorte. Suspensiva ("não devem"): viúvo sem inventário, viúva até 10 meses, divorciado sem partilha, tutor com tutelado.', b: null,
    p: 'Na suspensiva, prova-se ausência de prejuízo (ou nascimento do filho/inexistência de gravidez).' },
  { id: 'civ-3-10', d: 'Direito Civil', r: 3, t: 'Família',
    f: 'Presunção de paternidade após o fim do casamento.',
    v: 'Filhos nascidos até 300 dias depois da dissolução da sociedade conjugal.', b: 'art. 1.597 CC' },
  { id: 'civ-3-11', d: 'Direito Civil', r: 3, t: 'Família',
    f: 'Extinção x perda do poder familiar.',
    v: 'Extinção: morte, emancipação, maioridade, adoção ou decisão judicial. Perda: castigo imoderado, abandono, atos contrários à moral, entrega irregular para adoção, crimes graves contra o outro titular ou contra o filho.', b: null },
  { id: 'civ-3-12', d: 'Direito Civil', r: 3, t: 'Regime de bens',
    f: 'Regime de bens pode mudar depois do casamento?',
    v: 'Sim, por autorização judicial, a pedido motivado de ambos, ressalvados os direitos de terceiros.', b: 'art. 1.639, § 2º, CC' },
  { id: 'civ-3-13', d: 'Direito Civil', r: 3, t: 'Regime de bens',
    f: 'Separação obrigatória para maiores de 70 anos ainda é imposta?',
    v: 'Não. O STF decidiu que pode ser afastada por vontade expressa das partes; quem já casou assim pode mudar o regime.', b: 'art. 1.641, II, CC' },
  { id: 'civ-3-14', d: 'Direito Civil', r: 3, t: 'Regime de bens',
    f: 'Comunhão universal: o que não se comunica?',
    v: 'Bens doados ou herdados com cláusula de incomunicabilidade (e os sub-rogados), bens gravados de fideicomisso, dívidas anteriores ao casamento (salvo aprestos ou proveito comum), doações antenupciais com incomunicabilidade.', b: 'art. 1.668 CC' },
  { id: 'civ-3-15', d: 'Direito Civil', r: 3, t: 'Alimentos',
    f: 'Prisão civil por alimentos: prazo e condição.',
    v: '1 a 3 meses, para coagir (não é pena), se o devedor puder pagar e não justificar.', b: 'art. 528, § 3º, CPC',
    p: 'Preso por crime continua devendo alimentos (STJ).' },
  { id: 'civ-3-16', d: 'Direito Civil', r: 3, t: 'Alimentos',
    f: 'Alimentos gravídicos exigem prova da paternidade?',
    v: 'Não, bastam indícios de paternidade; valem até o nascimento.', b: null },
  { id: 'civ-3-17', d: 'Direito Civil', r: 3, t: 'Sucessões',
    f: 'Renúncia da herança pode ser parcial ou em favor de alguém?',
    v: 'Não. A renúncia é do todo e não há renúncia em favor de pessoa determinada. Funeral e atos de conservação não significam aceitação.', b: null },
  { id: 'civ-3-18', d: 'Direito Civil', r: 3, t: 'Sucessões',
    f: 'Indignidade x deserdação: forma e prazo.',
    v: 'Indignidade: qualquer herdeiro pede; declarada por sentença; 4 anos da abertura da sucessão. Deserdação: só de herdeiro necessário, por testamento com causa expressa; 4 anos da abertura do testamento.', b: 'arts. 1.814, 1.962 e 1.963 CC' },
  { id: 'civ-3-19', d: 'Direito Civil', r: 3, t: 'Sucessão legítima',
    f: 'Quando o cônjuge não concorre com os descendentes?',
    v: 'Na comunhão universal e na separação obrigatória. Na comunhão parcial, concorre só nos bens particulares. "Quem meia não herda, quem herda não meia."', b: 'art. 1.829, I, CC' },
  { id: 'civ-3-20', d: 'Direito Civil', r: 3, t: 'Sucessão legítima',
    f: 'Cônjuge concorre com ascendentes em qualquer regime?',
    v: 'Sim, independe do regime de bens. Sem descendentes nem ascendentes, herda tudo.', b: null },
  { id: 'civ-3-21', d: 'Direito Civil', r: 3, t: 'Sucessão legítima',
    f: 'Colaterais são herdeiros necessários?',
    v: 'Não, são facultativos, até o 4º grau, e podem ser excluídos por testamento. Necessários são descendentes, ascendentes e cônjuge.', b: 'arts. 1.845 e 1.850 CC' },
  { id: 'civ-3-22', d: 'Direito Civil', r: 3, t: 'Sucessão legítima',
    f: 'Direito de representação: onde ocorre?',
    v: 'Só na sucessão legítima: linha reta descendente e, na colateral, filhos de irmãos. Nunca na linha ascendente.', b: 'arts. 1.851, 1.852 e 1.855 CC' },
  { id: 'civ-3-23', d: 'Direito Civil', r: 3, t: 'Sucessão testamentária',
    f: 'Quanto o testador pode deixar livremente?',
    v: 'Com herdeiros necessários, 50%; sem eles, 100%.', b: 'art. 1.789 CC' },
  { id: 'civ-3-24', d: 'Direito Civil', r: 3, t: 'Sucessão testamentária',
    f: 'Quem tem 16 anos pode testar? E o testamento perde validade com incapacidade posterior?',
    v: 'Pode, sem assistência. A incapacidade superveniente não invalida o testamento, nem a capacidade posterior valida o do incapaz.', b: null },
  { id: 'civ-3-25', d: 'Direito Civil', r: 3, t: 'Sucessão testamentária',
    f: 'Prazo para impugnar a validade do testamento.',
    v: '5 anos do registro do testamento.', b: null },
  { id: 'civ-3-26', d: 'Direito Civil', r: 3, t: 'Sucessão testamentária',
    f: 'Tutor nomeado pelos pais em testamento prevalece sobre os avós?',
    v: 'Sim, a escolha dos pais (por testamento ou documento autêntico) prevalece sobre a ordem legal.', b: 'art. 1.729 CC' }
]);
