// Flashcards · Ética Profissional · Revisões 1, 2 e 3 do VDE (material em tabelas)
// Campos: d disciplina, r revisão, t tema, f frente, v verso, b dispositivo citado na revisão
// (sem b = "conferir"), p pegadinha, c conferir mesmo com b, n nota sobre divergência.
window.FC_VDE = (window.FC_VDE || []).concat([
  // ── Revisão 1 ──
  { id: 'eti-1-01', d: 'Ética Profissional', r: 1, t: 'Atividades da advocacia',
    f: 'Postular em juízo é privativo do advogado. Quais são as exceções?',
    v: 'Jus postulandi na Justiça do Trabalho (só Varas e TRTs), Juizados Especiais (até 20 SM no estadual e 60 SM no federal) e habeas corpus, que qualquer pessoa impetra.',
    b: 'Súmula 425 TST (jus postulandi)', p: 'Jus postulandi não vale no TST, na ação rescisória, na cautelar nem no mandado de segurança.' },
  { id: 'eti-1-02', d: 'Ética Profissional', r: 1, t: 'Atividades da advocacia',
    f: 'Consultoria e assessoria jurídica dependem de procuração ou de contrato escrito?',
    v: 'Não. Podem ser prestadas de forma verbal ou escrita, sem outorga de mandato e sem contrato formal de honorários.', b: null },
  { id: 'eti-1-03', d: 'Ética Profissional', r: 1, t: 'Atividades da advocacia',
    f: 'Atos e contratos constitutivos de pessoa jurídica precisam do visto de advogado? Há exceção?',
    v: 'Sim, antes do registro. A exceção são as microempresas e empresas de pequeno porte, dispensadas do visto.', b: null },
  { id: 'eti-1-04', d: 'Ética Profissional', r: 1, t: 'Atos nulos',
    f: 'Quais atos privativos de advogado são nulos?',
    v: 'Os praticados por quem não é inscrito na OAB e por advogado impedido (no limite do impedimento), suspenso, licenciado ou que exerça atividade incompatível.', b: null },
  { id: 'eti-1-05', d: 'Ética Profissional', r: 1, t: 'Mandato judicial',
    f: 'O advogado renunciou ao mandato. Por quanto tempo continua atuando?',
    v: 'Por 10 dias após a notificação, salvo se o cliente constituir outro advogado antes. A renúncia é comunicada ao cliente e ao juízo e não precisa de motivo.', b: null },
  { id: 'eti-1-06', d: 'Ética Profissional', r: 1, t: 'Mandato judicial',
    f: 'A revogação do mandato pelo cliente tira os honorários do advogado?',
    v: 'Não. Os honorários contratados continuam devidos, e os sucumbenciais são recebidos na proporção do trabalho feito.', b: null },
  { id: 'eti-1-07', d: 'Ética Profissional', r: 1, t: 'Mandato judicial',
    f: 'O mandato judicial se extingue pelo decurso do tempo?',
    v: 'Não, salvo se o contrário constar do instrumento.', b: null },
  { id: 'eti-1-08', d: 'Ética Profissional', r: 1, t: 'Substabelecimento',
    f: 'Substabelecimento com reserva x sem reserva de poderes: o que muda?',
    v: 'Com reserva: parcial e provisório, o advogado original mantém os poderes, e o substabelecido ajusta honorários com ele (não cobra direto do cliente). Sem reserva: total e definitivo, exige prévio e inequívoco conhecimento do cliente, e o novo advogado cobra direto do cliente.', b: null,
    p: 'Com reserva, o substabelecido não pode cobrar honorários do cliente sem intervenção de quem substabeleceu.' },
  { id: 'eti-1-09', d: 'Ética Profissional', r: 1, t: 'Inscrição na OAB',
    f: 'Quais são os requisitos para a inscrição como advogado?',
    v: 'Capacidade civil, diploma de Direito (estrangeiro revalidado), título de eleitor, quitação militar (homens), aprovação no Exame de Ordem, não exercer atividade incompatível, idoneidade moral e compromisso perante o Conselho.', b: null,
    p: 'Nacionalidade brasileira não é requisito.' },
  { id: 'eti-1-10', d: 'Ética Profissional', r: 1, t: 'Inscrição na OAB',
    f: 'Qual o quórum para declarar a inidoneidade moral de quem pede inscrição?',
    v: '2/3 dos votos de todos os membros do conselho competente. Quem foi condenado por crime infamante não atende ao requisito, salvo reabilitação judicial.', b: null },
  { id: 'eti-1-11', d: 'Ética Profissional', r: 1, t: 'Inscrição na OAB',
    f: 'Quando a inscrição suplementar passa a ser obrigatória?',
    v: 'Quando o advogado passa a atuar com habitualidade em outro Estado: mais de 5 causas novas por ano. Paga-se anuidade de cada inscrição.', b: null,
    p: 'Consultoria, assessoria, pareceres e atos constitutivos não contam para as 5 causas.' },
  { id: 'eti-1-12', d: 'Ética Profissional', r: 1, t: 'Inscrição na OAB',
    f: 'Transferência x inscrição suplementar?',
    v: 'Na transferência a inscrição principal anterior é cancelada e a nova vira principal (mudança completa de domicílio profissional). Na suplementar a anterior continua valendo.', b: null },
  { id: 'eti-1-13', d: 'Ética Profissional', r: 1, t: 'Inscrição na OAB',
    f: 'Cancelamento x licenciamento da inscrição: anuidade e retorno.',
    v: 'Cancelamento: definitivo, cessa a anuidade e o retorno exige nova inscrição, com outro número. Licenciamento: temporário, a anuidade só cessa se o advogado pedir, e ele volta com o mesmo número.', b: null },
  { id: 'eti-1-14', d: 'Ética Profissional', r: 1, t: 'Inscrição na OAB',
    f: 'Quais são as hipóteses de licenciamento da inscrição?',
    v: 'Pedido justificado, exercício temporário de atividade incompatível e doença mental considerada curável.', b: null,
    p: 'Atividade incompatível definitiva gera cancelamento, não licença.' },
  { id: 'eti-1-15', d: 'Ética Profissional', r: 1, t: 'Estágio profissional',
    f: 'Estágio profissional: duração e o que o estagiário pode fazer sozinho?',
    v: '2 anos, prorrogáveis por mais 1. Sozinho pode assinar petição de juntada, retirar e devolver autos (carga), obter certidões e praticar atos extrajudiciais com autorização ou substabelecimento do advogado.', b: null },
  { id: 'eti-1-16', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'O advogado preso pode falar com o cliente? E se a autoridade negar?',
    v: 'Pode se comunicar pessoal e reservadamente com o cliente preso, mesmo sem procuração e mesmo se incomunicável. A recusa gera nulidade absoluta do interrogatório ou depoimento e do que dele derivar.', b: null },
  { id: 'eti-1-17', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'Prisão em flagrante de advogado: o que é obrigatório?',
    v: 'Presença de representante da OAB na lavratura do auto, sob pena de nulidade, e comunicação expressa à Seccional.', b: null,
    n: 'A revisão diz que o advogado só é preso em flagrante por crime inafiançável; a regra do Estatuto vale para o flagrante por motivo ligado ao exercício da profissão.', c: true },
  { id: 'eti-1-18', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'Quando a inviolabilidade do escritório pode ser quebrada?',
    v: 'Havendo indícios de autoria e materialidade de crime do próprio advogado, por decisão judicial motivada, com mandado específico cumprido na presença de representante da OAB.', b: null,
    p: 'Documentos de clientes não podem ser usados, salvo se o cliente for investigado como coautor ou partícipe do mesmo crime.' },
  { id: 'eti-1-19', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'O advogado pode fazer colaboração premiada contra cliente?',
    v: 'Não, nem contra ex-cliente. A violação sujeita a processo disciplinar, podendo levar à exclusão.', b: null },
  { id: 'eti-1-20', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'O juiz não chegou à audiência. Quando o advogado pode se retirar?',
    v: 'Após 30 minutos do horário marcado, comunicando o fato em juízo por petição protocolizada.', b: 'art. 7º, XX, EAOAB (citado na Revisão 1 de Proc. do Trabalho)',
    p: 'Não vale se o juiz estiver em outra audiência. No processo do trabalho a CLT prevê 15 minutos (art. 815, p. único).' },
  { id: 'eti-1-21', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'Onde o advogado fica preso antes do trânsito em julgado?',
    v: 'Em sala de Estado Maior, com instalações condignas; se não houver, em prisão domiciliar.', b: null },
  { id: 'eti-1-22', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'Para examinar autos, o advogado precisa de procuração?',
    v: 'Não, para autos findos ou em andamento sem sigilo, em qualquer órgão dos Poderes ou da Administração, podendo copiar e tomar apontamentos. Em autos sob sigilo, precisa de procuração.', b: null,
    p: 'A autoridade só pode restringir o acesso a diligências em andamento e ainda não documentadas, se houver risco à investigação.' },
  { id: 'eti-1-23', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'Imunidade profissional na prova: como responder?',
    v: 'Se a questão pedir o entendimento do STF, não há imunidade (o § 2º do art. 7º foi revogado pela Lei 14.365/2022). Se pedir o EAOAB ou a CF, há imunidade.', b: 'art. 133 CF; art. 7º, § 2º, EAOAB (revogado)' },
  { id: 'eti-1-24', d: 'Ética Profissional', r: 1, t: 'Direitos e prerrogativas',
    f: 'Advogada adotante ou que deu à luz: qual direito ela tem além da preferência nas audiências?',
    v: 'Suspensão dos prazos processuais quando for a única patrona da causa, mediante notificação escrita ao cliente. Gestante: não passa por detector de metais/raio X e tem vaga reservada; lactante: acesso a creche ou local adequado.', b: null },
  { id: 'eti-1-25', d: 'Ética Profissional', r: 1, t: 'Desagravo público',
    f: 'Desagravo: quem pede e o ofendido pode dispensá-lo?',
    v: 'O próprio ofendido, qualquer pessoa ou o Conselho de ofício. Independe da concordância do ofendido, que não pode dispensá-lo.', b: null,
    p: 'O relator pode propor arquivamento se a ofensa for pessoal, sem relação com a profissão, ou mera crítica doutrinária, política ou religiosa.' },
  { id: 'eti-1-26', d: 'Ética Profissional', r: 1, t: 'Desagravo público',
    f: 'Desagravo: prazo da sessão e competência quando o ofendido é Conselheiro Federal?',
    v: 'A sessão ocorre em até 30 dias, de preferência no local da ofensa. Ofensa a Conselheiro Federal, Presidente de Seccional ou com repercussão nacional: Conselho Federal.', b: null },
  { id: 'eti-1-27', d: 'Ética Profissional', r: 1, t: 'Sociedade de advogados',
    f: 'Sociedade de advogados: personalidade jurídica e onde se registra?',
    v: 'Adquire personalidade com o registro dos atos constitutivos no Conselho Seccional da sede. Nunca em Junta Comercial ou cartório; não pode ser empresária.', b: null },
  { id: 'eti-1-28', d: 'Ética Profissional', r: 1, t: 'Sociedade de advogados',
    f: 'Qual a responsabilidade dos sócios na sociedade simples e na unipessoal de advocacia?',
    v: 'Ilimitada e subsidiária nas duas. A unipessoal usa o nome do titular + "Sociedade Individual de Advocacia".', b: null },
  { id: 'eti-1-29', d: 'Ética Profissional', r: 1, t: 'Sociedade de advogados',
    f: 'A sociedade de advogados paga anuidade?',
    v: 'Não. A anuidade é cobrada só dos advogados (pessoas físicas) — STJ, out./2023.', b: null },
  { id: 'eti-1-30', d: 'Ética Profissional', r: 1, t: 'Sociedade de advogados',
    f: 'Quantas sociedades o advogado pode integrar na mesma Seccional?',
    v: 'Uma (sede ou filial) por Seccional, e só uma sociedade unipessoal. Na Seccional da filial, os sócios fazem inscrição suplementar.', b: null },
  { id: 'eti-1-31', d: 'Ética Profissional', r: 1, t: 'Sociedade de advogados',
    f: 'Advogados da mesma sociedade podem representar clientes com interesses opostos?',
    v: 'Não, em juízo ou fora dele. Vale também para quem atua em cooperação recíproca permanente.', b: null },
  { id: 'eti-1-32', d: 'Ética Profissional', r: 1, t: 'Advogado empregado',
    f: 'Advogado empregado em dedicação exclusiva: jornada e adicional noturno.',
    v: 'Dedicação exclusiva tem de constar no contrato; limite de 8 h diárias e 40 h semanais. Adicional noturno mínimo de 25% para o trabalho entre 20h e 5h.', b: 'art. 20 EAOAB (Lei 14.365/2022)' },
  { id: 'eti-1-33', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'Honorários convencionais sem forma de pagamento definida: como se paga?',
    v: '1/3 no início, 1/3 durante o andamento e 1/3 no final.', b: null },
  { id: 'eti-1-34', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'Percentual dos honorários sucumbenciais no CPC e na CLT?',
    v: 'CPC: 10% a 20%. CLT: 5% a 15%. Na procedência parcial, são fixados reciprocamente e é vedada a compensação.', b: null },
  { id: 'eti-1-35', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'O cliente fez acordo direto com a parte contrária. O advogado perde os honorários?',
    v: 'Não. Honorários contratados não diminuem por solução extrajudicial (mediação, conciliação, acordo), e o acordo não pode prejudicar o crédito sem consentimento do advogado.', b: null },
  { id: 'eti-1-36', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'Contrato de honorários verbal x escrito na hora de cobrar?',
    v: 'Escrito (ou decisão que fixa/arbitra) é título executivo: execução direta. Verbal: ação de cobrança.', b: null,
    p: 'Não pode sacar duplicata nem protestar fatura; cheque e nota promissória podem ser protestados após tentativa amigável.' },
  { id: 'eti-1-37', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'Bloqueio universal dos bens do cliente: quanto o advogado pode liberar para honorários?',
    v: 'Até 20% dos bens bloqueados, para honorários e reembolso de despesas da defesa.', b: 'art. 24-A EAOAB (Gabaritaço)', p: 'Não vale nas causas da Lei de Drogas (Lei 11.343/2006).' },
  { id: 'eti-1-38', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'Cláusula quota litis: forma de pagamento e limite?',
    v: 'Pagamento em dinheiro, salvo participação em bens prevista em contrato escrito prévio. Somada à sucumbência, não pode passar da vantagem obtida pelo cliente.', b: null },
  { id: 'eti-1-39', d: 'Ética Profissional', r: 1, t: 'Honorários',
    f: 'Prescrição da cobrança de honorários e da prestação de contas?',
    v: '5 anos para as duas. Conta do vencimento do contrato, do trânsito da decisão que fixa os honorários, do fim do serviço extrajudicial, da desistência/transação ou da renúncia/revogação do mandato.', b: null },

  // ── Revisão 2 ──
  { id: 'eti-2-01', d: 'Ética Profissional', r: 2, t: 'Incompatibilidades e impedimentos',
    f: 'Incompatibilidade x impedimento?',
    v: 'Incompatibilidade proíbe totalmente a advocacia, até em causa própria, e persiste no afastamento temporário do cargo. Impedimento é proibição parcial: o advogado pode advogar com restrições.', b: null },
  { id: 'eti-2-02', d: 'Ética Profissional', r: 2, t: 'Incompatibilidades e impedimentos',
    f: 'Cite hipóteses de incompatibilidade.',
    v: 'Chefes do Executivo e membros da Mesa do Legislativo; membros do Judiciário, MP e Tribunais de Contas; cargos de direção na Administração; cargos ligados ao Judiciário e a cartórios; atividade policial; funções de lançamento, arrecadação ou fiscalização de tributos; direção ou gerência de instituição financeira.', b: null,
    p: 'Cargo de direção sem poder de decisão relevante e direção de magistério jurídico não geram incompatibilidade.' },
  { id: 'eti-2-03', d: 'Ética Profissional', r: 2, t: 'Incompatibilidades e impedimentos',
    f: 'Policial ou militar pode advogar em causa própria?',
    v: 'Não. O STF declarou inconstitucionais os §§ 3º e 4º do art. 28, que permitiam.', b: 'art. 28, §§ 3º e 4º, EAOAB (inconstitucionais)' },
  { id: 'eti-2-04', d: 'Ética Profissional', r: 2, t: 'Incompatibilidades e impedimentos',
    f: 'Servidor público é impedido de advogar contra quem?',
    v: 'Contra a Fazenda Pública que o remunera ou à qual se vincula a entidade empregadora.', b: null },
  { id: 'eti-2-05', d: 'Ética Profissional', r: 2, t: 'Incompatibilidades e impedimentos',
    f: 'Parlamentar é impedido ou incompatível?',
    v: 'Impedido de advogar contra ou a favor de pessoas jurídicas de direito público, empresas públicas, SEM, fundações, paraestatais e concessionárias. Se assume a Mesa, fica incompatível enquanto estiver nela.', b: null },
  { id: 'eti-2-06', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'A censura é publicada? Pode virar advertência?',
    v: 'É sigilosa, mesmo após o trânsito em julgado. Com atenuante, converte-se em advertência sem registro nos assentamentos.', b: null },
  { id: 'eti-2-07', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'Cite infrações punidas com censura.',
    v: 'Captar clientela ou usar agenciador, assinar peça sem participar, violar sigilo sem justa causa, negociar com a parte contrária sem ciência do advogado dela, abandonar a causa sem motivo, descumprir o CED, estagiário exceder a habilitação.', b: null },
  { id: 'eti-2-08', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'Suspensão: duração e exceções.',
    v: 'De 30 dias a 12 meses. Em dívida com a OAB ou com cliente, dura até a quitação corrigida; em inépcia profissional, até passar em novas provas de habilitação. A anuidade continua devida.', b: null,
    p: 'O STF julgou inconstitucional suspender só por inadimplência de anuidades.' },
  { id: 'eti-2-09', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'Cite infrações punidas com suspensão.',
    v: 'Locupletar-se à custa do cliente, recusar-se a prestar contas, reter ou extraviar autos, receber valores de terceiros sem autorização, conduta incompatível (embriaguez, jogo, toxicomania habitual), reincidência e assédio moral, sexual ou discriminação.', b: 'Lei 14.612/2023 (assédio)' },
  { id: 'eti-2-10', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'Exclusão: quórum e hipóteses.',
    v: 'Manifestação favorável de 2/3 do Conselho Seccional. Hipóteses: falsificar requisito de inscrição, tornar-se moralmente inidôneo, crime infamante e 3 suspensões.', b: null },
  { id: 'eti-2-11', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'A multa disciplinar pode ser aplicada sozinha? Qual o valor?',
    v: 'Não, é acessória: cumula com censura ou suspensão. Vai de 1 a 10 anuidades.', b: null },
  { id: 'eti-2-12', d: 'Ética Profissional', r: 2, t: 'Infrações e sanções',
    f: 'Reabilitação e prescrição disciplinar: prazos.',
    v: 'Reabilitação: pedido 1 ano após cumprir a sanção (se veio de crime, depende da reabilitação criminal). A pretensão punitiva prescreve em 5 anos da constatação oficial do fato.', b: null },
  { id: 'eti-2-13', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'O processo disciplinar admite denúncia anônima? É público?',
    v: 'Não admite: começa de ofício ou por representação. Tramita em sigilo até o fim; depois a decisão é pública, salvo a censura.', b: null },
  { id: 'eti-2-14', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'Onde tramita o processo disciplinar? E na suspensão preventiva?',
    v: 'No Conselho Seccional do local da infração. Com suspensão preventiva, no Conselho da inscrição principal, e o processo deve terminar em 90 dias.', b: null },
  { id: 'eti-2-15', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'Suspensão preventiva: quem aplica e em que hipótese?',
    v: 'O TED da inscrição principal, quando a conduta tem repercussão prejudicial à dignidade da advocacia, depois de ouvir o advogado em sessão especial (se não comparecer, aplica mesmo assim).', b: null },
  { id: 'eti-2-16', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'Prazo para manifestações nos processos da OAB e início da contagem?',
    v: '15 dias úteis, do primeiro dia útil após a publicação ou o recebimento da notificação. Por ofício reservado ou notificação pessoal, do primeiro dia útil após a juntada do AR.', b: null },
  { id: 'eti-2-17', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'Advogado representado não é encontrado ou é revel. O que acontece?',
    v: 'O Presidente da Seccional designa defensor dativo.', b: null },
  { id: 'eti-2-18', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'Recursos no processo disciplinar têm efeito suspensivo? Quando cabe recurso ao Conselho Federal?',
    v: 'Sim, suspensivo. Ao Conselho Federal: decisão não unânime do Seccional, ou unânime que contrarie lei, decisão do CF ou de outro Seccional, Regulamento Geral, CED ou Provimentos.', b: null },
  { id: 'eti-2-19', d: 'Ética Profissional', r: 2, t: 'Processo disciplinar',
    f: 'TAC na OAB: quando cabe?',
    v: 'Publicidade irregular ou infração punível com censura sem repercussão negativa, sem condenação transitada, com uma só infração e sem TAC nos últimos 3 anos.', b: 'Provimento 200/2020; arts. 47-A e 58-A CED' },

  // ── Revisão 3 ──
  { id: 'eti-3-01', d: 'Ética Profissional', r: 3, t: 'Relações com o cliente',
    f: 'O advogado pode aceitar procuração de quem já tem advogado?',
    v: 'Não, salvo motivo justificado ou urgência comprovada (como uma liminar para evitar prejuízo imediato).', b: null },
  { id: 'eti-3-02', d: 'Ética Profissional', r: 3, t: 'Relações com o cliente',
    f: 'O advogado pode ser preposto e patrono do mesmo cliente no mesmo processo?',
    v: 'Não, é vedado acumular as duas funções.', b: null },
  { id: 'eti-3-03', d: 'Ética Profissional', r: 3, t: 'Relações com o cliente',
    f: 'O cliente exige uma ação infundada. O que o advogado faz?',
    v: 'Recusa e explica os riscos: ele escolhe o caminho jurídico adequado. Participar de lide temerária gera responsabilidade disciplinar e civil.', b: null },
  { id: 'eti-3-04', d: 'Ética Profissional', r: 3, t: 'Estrutura da OAB',
    f: 'Composição do Conselho Federal.',
    v: 'Delegações de cada unidade da federação, com 3 conselheiros federais cada, mais os ex-presidentes (membros honorários vitalícios) e o Presidente nacional.', b: null },
  { id: 'eti-3-05', d: 'Ética Profissional', r: 3, t: 'Estrutura da OAB',
    f: 'Quantos conselheiros tem um Conselho Seccional?',
    v: 'Até 3 mil inscritos, até 40; acima disso, +1 a cada 3 mil, limitado a 90. Ex-presidentes e o presidente do Instituto dos Advogados local têm só voz.', b: 'art. 58 EAOAB (competências)' },
  { id: 'eti-3-06', d: 'Ética Profissional', r: 3, t: 'Estrutura da OAB',
    f: 'Caixa de Assistência dos Advogados: quando é criada e quanto recebe?',
    v: 'Quando a Seccional tem mais de 1.500 inscritos; tem personalidade jurídica própria e recebe metade das anuidades. Intervenção exige 2/3 dos conselheiros.', b: null },
  { id: 'eti-3-07', d: 'Ética Profissional', r: 3, t: 'Estrutura da OAB',
    f: 'Subseção: personalidade jurídica e requisitos.',
    v: 'Não tem personalidade jurídica. Exige ao menos 15 advogados com domicílio profissional na área; com mais de 100, pode ter Conselho próprio.', b: null },
  { id: 'eti-3-08', d: 'Ética Profissional', r: 3, t: 'Eleições na OAB',
    f: 'Eleições da OAB: quando, voto obrigatório e multa.',
    v: 'Segunda quinzena de novembro do último ano do mandato, voto direto e obrigatório. Faltar sem justificativa gera multa de 20% da anuidade.', b: null },
  { id: 'eti-3-09', d: 'Ética Profissional', r: 3, t: 'Eleições na OAB',
    f: 'Tempo mínimo de advocacia para concorrer.',
    v: '3 anos para Conselheiro Seccional e das Subseções; 5 anos para os demais cargos. Também: estar regular, sem cargo ad nutum e sem condenação disciplinar (salvo reabilitação).', b: null },
  { id: 'eti-3-10', d: 'Ética Profissional', r: 3, t: 'Eleições na OAB',
    f: 'Regras de composição das chapas.',
    v: 'Chapa completa, com 50% de cada gênero e 30% de advogados negros (titulares e suplentes).', b: null },
  { id: 'eti-3-11', d: 'Ética Profissional', r: 3, t: 'Eleições na OAB',
    f: 'Mandato na OAB: duração e posse.',
    v: '3 anos, a partir de 1º de janeiro do ano seguinte. Conselho Federal: eleição indireta em 31 de janeiro e posse em 1º de fevereiro. Os cargos não são remunerados.', b: null },
  { id: 'eti-3-12', d: 'Ética Profissional', r: 3, t: 'Publicidade',
    f: 'Publicidade em rádio, cinema e televisão é permitida?',
    v: 'Não. Também são vedadas inscrições em muros, veículos, elevadores e espaços públicos, e divulgar advocacia junto com outra atividade.', b: null,
    p: 'Participar de programa ou entrevista é permitido, com fim só educativo, sem autopromoção e sem comentar métodos de colegas.' },
  { id: 'eti-3-13', d: 'Ética Profissional', r: 3, t: 'Publicidade',
    f: 'Pode impulsionar posts nas redes sociais?',
    v: 'Sim, desde o Provimento 205/2021, se o conteúdo for informativo, sem apresentar o advogado como "melhor" ou "mais rápido".', b: 'Provimento 205/2021' },
  { id: 'eti-3-14', d: 'Ética Profissional', r: 3, t: 'Publicidade',
    f: 'Placa na fachada do escritório é permitida?',
    v: 'Sim, para identificar o escritório, com sobriedade e discrição.', b: 'art. 40, p. único, CED' },
  { id: 'eti-3-15', d: 'Ética Profissional', r: 3, t: 'Publicidade',
    f: 'O advogado pode debater na mídia causa de outro advogado ou divulgar lista de clientes?',
    v: 'Não, as duas condutas são vedadas.', b: null },
  { id: 'eti-3-16', d: 'Ética Profissional', r: 3, t: 'Sigilo profissional',
    f: 'O cliente autorizou. O advogado pode testemunhar sobre o que soube no exercício da profissão?',
    v: 'Não é obrigado, mesmo com autorização do cliente. A quebra só cabe com justa causa: grave ameaça à vida ou à honra, ou defesa própria do advogado.', b: null }
]);
