// Flashcards · Direito Penal · Revisões 1, 2 e 3 do VDE (material em tabelas)
// Campos: ver fc-etica.js.
window.FC_VDE = (window.FC_VDE || []).concat([
  // ── Revisão 1 ──
  { id: 'pen-1-01', d: 'Direito Penal', r: 1, t: 'Lei penal no tempo',
    f: 'Lei posterior mais benéfica alcança sentença transitada em julgado?',
    v: 'Sim, a lei que de qualquer modo favorece o agente retroage, mesmo após o trânsito. A abolitio criminis extingue a punibilidade.', b: null },
  { id: 'pen-1-02', d: 'Direito Penal', r: 1, t: 'Lei penal no tempo',
    f: 'Lei mais grave entra em vigor durante crime continuado ou permanente. Aplica-se?',
    v: 'Sim, se a vigência for anterior à cessação da continuidade ou da permanência.', b: 'Súmula 711 STF' },
  { id: 'pen-1-03', d: 'Direito Penal', r: 1, t: 'Lei penal no tempo',
    f: 'Lei temporária e lei excepcional têm ultratividade?',
    v: 'Sim: aplicam-se aos fatos praticados durante a vigência, mesmo depois de revogadas e ainda que mais graves.', b: null },
  { id: 'pen-1-04', d: 'Direito Penal', r: 1, t: 'Tempo e lugar do crime',
    f: 'Teoria adotada para o tempo e para o lugar do crime (LUTA).',
    v: 'Tempo: atividade (momento da ação ou omissão). Lugar: ubiquidade (ação ou resultado). Exceções de lugar: Juizados (atividade, art. 63 da Lei 9.099/95) e crimes plurilocais (resultado, art. 70 CPP).', b: 'art. 63 Lei 9.099/95; art. 70 CPP' },
  { id: 'pen-1-05', d: 'Direito Penal', r: 1, t: 'Lei penal no espaço',
    f: 'Extraterritorialidade incondicionada: hipóteses.',
    v: 'Crimes contra a vida ou liberdade do Presidente; contra patrimônio ou fé pública dos entes e da administração indireta; contra a administração por quem está a seu serviço; genocídio por brasileiro ou domiciliado no Brasil. Pune-se mesmo se absolvido ou condenado no estrangeiro.', b: 'art. 7º, I e § 1º, CP' },
  { id: 'pen-1-06', d: 'Direito Penal', r: 1, t: 'Lei penal no espaço',
    f: 'Condições da extraterritorialidade condicionada.',
    v: 'Entrar no território nacional, fato punível também no país, crime extraditável, não absolvido nem cumprido pena lá, não perdoado nem extinta a punibilidade. Crime de estrangeiro contra brasileiro exige ainda extradição negada ou não pedida e requisição do Ministro da Justiça.', b: 'art. 7º, §§ 2º e 3º, CP' },
  { id: 'pen-1-07', d: 'Direito Penal', r: 1, t: 'Fato típico',
    f: 'Desistência voluntária x arrependimento eficaz x arrependimento posterior.',
    v: 'Desistência: interrompe a execução. Eficaz: esgota os atos e impede o resultado. A revisão classifica os dois como causas de exclusão da tipicidade. Posterior: repara o dano ou restitui até o recebimento da denúncia, em crime sem violência ou grave ameaça; reduz a pena de 1/3 a 2/3.', b: null },
  { id: 'pen-1-08', d: 'Direito Penal', r: 1, t: 'Fato típico',
    f: 'Crime impossível.',
    v: 'Ineficácia absoluta do meio ou absoluta impropriedade do objeto (ex.: matar com arma de brinquedo). Não há crime.', b: null },
  { id: 'pen-1-09', d: 'Direito Penal', r: 1, t: 'Erro de tipo',
    f: 'Erro de tipo escusável x inescusável.',
    v: 'Escusável (inevitável): exclui dolo e culpa. Inescusável (evitável): exclui o dolo, mas responde por culpa se houver modalidade culposa.', b: null },
  { id: 'pen-1-10', d: 'Direito Penal', r: 1, t: 'Erro de tipo',
    f: 'Erro sobre a pessoa x erro na execução.',
    v: 'Sobre a pessoa: confunde a vítima, a execução é correta e a vítima visada não corre perigo. Na execução (aberratio ictus): identifica bem a vítima, mas falha a execução e atinge outra.', b: null },
  { id: 'pen-1-11', d: 'Direito Penal', r: 1, t: 'Nexo causal',
    f: 'Concausa absolutamente independente: por que o agente responde?',
    v: 'Rompe o nexo: responde só pelo que praticou (em regra, tentativa), não pelo resultado. Nas relativamente independentes preexistentes e concomitantes, responde pelo resultado.', b: null },
  { id: 'pen-1-12', d: 'Direito Penal', r: 1, t: 'Dolo e culpa',
    f: 'Dolo eventual x culpa consciente.',
    v: 'Dolo eventual: prevê e assume o risco, indiferente ao resultado. Culpa consciente: prevê, mas acredita sinceramente que vai evitar.', b: null },
  { id: 'pen-1-13', d: 'Direito Penal', r: 1, t: 'Tentativa',
    f: 'Quais crimes não admitem tentativa?',
    v: 'Culposos, omissivos próprios, habituais, unissubsistentes e preterdolosos. Na contravenção, a tentativa não é punível.', b: 'art. 4º LCP' },
  { id: 'pen-1-14', d: 'Direito Penal', r: 1, t: 'Ilicitude',
    f: 'Requisitos da legítima defesa.',
    v: 'Injusta agressão, atual ou iminente, a direito próprio ou de outrem, repelida com uso moderado dos meios necessários.', b: 'art. 25 CP',
    p: 'Defender bem disponível de terceiro exige o consentimento dele.' },
  { id: 'pen-1-15', d: 'Direito Penal', r: 1, t: 'Ilicitude',
    f: 'Estado de necessidade: e se o bem salvo vale menos que o sacrificado?',
    v: 'Há crime, com pena reduzida de 1/3 a 2/3. Só exclui a ilicitude se o bem preservado valer igual ou mais.', b: null },
  { id: 'pen-1-16', d: 'Direito Penal', r: 1, t: 'Ilicitude',
    f: 'Ataque de animal: legítima defesa ou estado de necessidade?',
    v: 'Ataque espontâneo do animal: estado de necessidade. Animal usado como instrumento por alguém: legítima defesa.', b: null },
  { id: 'pen-1-17', d: 'Direito Penal', r: 1, t: 'Culpabilidade',
    f: 'Emoção, paixão e embriaguez voluntária excluem a imputabilidade?',
    v: 'Não. Exclui: menoridade, doença mental ou desenvolvimento incompleto/retardado e embriaguez completa por caso fortuito ou força maior.', b: 'art. 28 CP' },
  { id: 'pen-1-18', d: 'Direito Penal', r: 1, t: 'Culpabilidade',
    f: 'Embriaguez acidental completa x incompleta x preordenada.',
    v: 'Acidental completa: isenta de pena. Acidental incompleta: reduz de 1/3 a 2/3. Preordenada: não exclui e é agravante genérica.', b: 'art. 28, §§ 1º e 2º; art. 61, II, "l", CP' },
  { id: 'pen-1-19', d: 'Direito Penal', r: 1, t: 'Culpabilidade',
    f: 'Erro de proibição escusável x inescusável.',
    v: 'Escusável: exclui a culpabilidade (isenta de pena). Inescusável: responde pelo crime doloso com pena reduzida de 1/6 a 1/3.', b: null,
    p: 'Erro de tipo: não sabe o que faz (exclui o crime). Erro de proibição: sabe o que faz, mas acha que é lícito (exclui a pena).' },
  { id: 'pen-1-20', d: 'Direito Penal', r: 1, t: 'Culpabilidade',
    f: 'Coação moral irresistível e obediência hierárquica excluem o quê?',
    v: 'A culpabilidade, por inexigibilidade de conduta diversa. A obediência exige ordem não manifestamente ilegal.', b: null },
  { id: 'pen-1-21', d: 'Direito Penal', r: 1, t: 'Concurso de crimes',
    f: 'Concurso formal próprio x impróprio.',
    v: 'Próprio (sem desígnios autônomos): exasperação, pena mais grave + 1/6 a 1/2. Impróprio (desígnios autônomos): somam-se as penas.', b: null },
  { id: 'pen-1-22', d: 'Direito Penal', r: 1, t: 'Concurso de crimes',
    f: 'Crime continuado: aumento comum e específico.',
    v: 'Comum: pena de um crime + 1/6 a 2/3. Crimes dolosos com violência ou grave ameaça: até o triplo.', b: null },
  { id: 'pen-1-23', d: 'Direito Penal', r: 1, t: 'Concurso de crimes',
    f: 'Concurso material: sistema de pena.',
    v: 'Cúmulo material: somam-se as penas. Várias condutas, vários crimes.', b: null, c: true,
    n: 'A revisão chama de "concurso material benéfico" a regra de não somar as penas; na lei, a regra do cúmulo mais benéfico é a do concurso formal. Conferir.' },
  { id: 'pen-1-24', d: 'Direito Penal', r: 1, t: 'Concurso de pessoas',
    f: 'Requisitos do concurso de pessoas.',
    v: 'Pluralidade de agentes, relevância causal das condutas, vínculo subjetivo e unidade de infração.', b: null },
  { id: 'pen-1-25', d: 'Direito Penal', r: 1, t: 'Concurso de pessoas',
    f: 'Participação de menor importância e cooperação dolosamente distinta.',
    v: 'Menor importância: reduz de 1/6 a 1/3. Quem quis crime menos grave responde por ele, com pena aumentada até metade se o resultado mais grave era previsível.', b: null },
  { id: 'pen-1-26', d: 'Direito Penal', r: 1, t: 'Concurso de pessoas',
    f: 'O que se comunica entre coautores?',
    v: 'Elementares e circunstâncias objetivas, se conhecidas (ex.: ser funcionário público no peculato). Circunstâncias pessoais não se comunicam (confissão, menoridade, reincidência).', b: 'art. 312, § 1º, CP (exemplo)' },
  { id: 'pen-1-27', d: 'Direito Penal', r: 1, t: 'Extinção da punibilidade',
    f: 'Anistia x graça x indulto.',
    v: 'Anistia: lei do Congresso, apaga o fato, antes ou depois da sentença. Graça: individual, do Presidente, a pedido. Indulto: coletivo, por decreto presidencial. Graça e indulto não apagam o crime.', b: null },
  { id: 'pen-1-28', d: 'Direito Penal', r: 1, t: 'Prescrição',
    f: 'Tabela da prescrição pela pena máxima.',
    v: '< 1 ano: 3 anos. 1 a 2: 4. > 2 a 4: 8. > 4 a 8: 12. > 8 a 12: 16. > 12: 20.', b: null },
  { id: 'pen-1-29', d: 'Direito Penal', r: 1, t: 'Prescrição',
    f: 'Início da prescrição antes do trânsito.',
    v: 'Da consumação; na tentativa, do último ato; no permanente, da cessação; na bigamia e falsificação de registro civil, do conhecimento; em crime sexual ou violência contra criança/adolescente, dos 18 anos da vítima.', b: null },
  { id: 'pen-1-30', d: 'Direito Penal', r: 1, t: 'Prescrição',
    f: 'Causas interruptivas da prescrição punitiva.',
    v: 'Recebimento da denúncia ou queixa, pronúncia, decisão que confirma a pronúncia, publicação de sentença ou acórdão condenatórios recorríveis e trânsito em julgado.', b: null },
  { id: 'pen-1-31', d: 'Direito Penal', r: 1, t: 'Prescrição',
    f: 'Prescrição retroativa: termo inicial possível.',
    v: 'Regula-se pela pena aplicada após trânsito para a acusação e nunca pode ter termo inicial anterior à denúncia ou queixa.', b: null },
  { id: 'pen-1-32', d: 'Direito Penal', r: 1, t: 'Prescrição',
    f: 'Quando o prazo prescricional cai pela metade?',
    v: 'Agente menor de 21 na data do fato ou maior de 70 na data da sentença.', b: null },

  // ── Revisão 2 ──
  { id: 'pen-2-01', d: 'Direito Penal', r: 2, t: 'Crimes contra a vida',
    f: 'Homicídio privilegiado: hipóteses.',
    v: 'Relevante valor social ou moral, ou domínio de violenta emoção logo após injusta provocação da vítima.', b: null },
  { id: 'pen-2-02', d: 'Direito Penal', r: 2, t: 'Crimes contra a vida',
    f: 'Feminicídio: quando há razões da condição do sexo feminino?',
    v: 'Violência doméstica e familiar, ou menosprezo e discriminação à condição de mulher.', b: 'art. 121-A CP (Revisão 3)' },
  { id: 'pen-2-03', d: 'Direito Penal', r: 2, t: 'Crimes contra a vida',
    f: 'Aumento do feminicídio (1/3 até metade): hipóteses.',
    v: 'Gestação ou 3 meses pós-parto, vítima mãe de criança/adolescente/PcD, vítima menor de 14, maior de 60 ou com deficiência, na presença de descendente ou ascendente, descumprindo medida protetiva, ou com meio cruel, traição ou arma de uso restrito.', b: null },
  { id: 'pen-2-04', d: 'Direito Penal', r: 2, t: 'Crimes contra a vida',
    f: 'Induzimento ao suicídio pela internet: o que muda?',
    v: 'Pena aumentada até o dobro se feito por rede de computadores, rede social ou transmissão em tempo real; em dobro se o agente lidera grupo virtual. Duplica também por motivo egoístico, torpe ou fútil e se a vítima é menor ou tem resistência diminuída.', b: null },
  { id: 'pen-2-05', d: 'Direito Penal', r: 2, t: 'Crimes contra a vida',
    f: 'Infanticídio: conceito e pena.',
    v: 'Mãe que mata o filho durante ou logo após o parto, sob influência do estado puerperal. Detenção de 2 a 6 anos.', b: null, c: true,
    n: 'A revisão diz que o terceiro que participa responde por homicídio; a própria Revisão 1 ensina que elementares se comunicam ao coautor que as conhece. Conferir a posição cobrada.' },
  { id: 'pen-2-06', d: 'Direito Penal', r: 2, t: 'Crimes contra a vida',
    f: 'Aborto com consentimento x por terceiro sem consentimento: penas e qualificadoras.',
    v: 'Gestante ou com consentimento: detenção de 1 a 3 anos. Terceiro sem consentimento: reclusão de 3 a 10. Lesão grave na gestante: +1/3; morte: pena em dobro.', b: 'arts. 124 a 127 CP' },
  { id: 'pen-2-07', d: 'Direito Penal', r: 2, t: 'Crimes contra a honra',
    f: 'Calúnia x difamação x injúria.',
    v: 'Calúnia: fato falso definido como crime (honra objetiva). Difamação: fato ofensivo à reputação (honra objetiva). Injúria: ofensa à dignidade ou decoro (honra subjetiva). Consumam-se quando terceiro toma conhecimento (calúnia, difamação) ou a vítima (injúria).', b: 'arts. 138 a 140 CP' },
  { id: 'pen-2-08', d: 'Direito Penal', r: 2, t: 'Crimes contra a honra',
    f: 'Onde cabe exceção da verdade?',
    v: 'Na calúnia (salvo as hipóteses do art. 138, § 3º) e na difamação contra funcionário público relativa às funções. Nunca na injúria.', b: 'art. 138, § 3º, CP; Súmula 396 STF' },
  { id: 'pen-2-09', d: 'Direito Penal', r: 2, t: 'Crimes contra a honra',
    f: 'Injúria racial hoje: onde está e características.',
    v: 'Na Lei 7.716/89 (Lei 14.532/2023). Ação pública incondicionada, imprescritível, inafiançável, reclusão de 2 a 5 anos. Novatio legis in pejus: não retroage.', b: 'Lei 7.716/89, art. 2º-A' },
  { id: 'pen-2-10', d: 'Direito Penal', r: 2, t: 'Crimes contra a honra',
    f: 'Crime contra a honra pelas redes sociais e mediante paga.',
    v: 'Redes sociais: pena em triplo. Paga ou promessa de recompensa: em dobro. Contra Presidente, funcionário em razão da função, na presença de várias pessoas ou contra vulneráveis: +1/3.', b: null },
  { id: 'pen-2-11', d: 'Direito Penal', r: 2, t: 'Crimes contra a honra',
    f: 'Ação penal nos crimes contra a honra.',
    v: 'Injúria real com lesão e injúria racial: pública incondicionada. Contra Presidente ou chefe de governo estrangeiro: requisição do Ministro da Justiça. Contra funcionário em razão da função: representação ou queixa (legitimidade concorrente).', b: null },
  { id: 'pen-2-12', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Furto de uso é crime? E o furto mediante fraude?',
    v: 'Furto de uso não é crime para a maioria (falta ânimo de assenhoreamento). Furto mediante fraude: a fraude burla a vigilância para subtrair.', b: null },
  { id: 'pen-2-13', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Roubo majorado: hipóteses.',
    v: 'Arma de fogo ou arma branca, concurso de pessoas, restrição de liberdade da vítima, transporte de valores ou de carga, entre outras.', b: null },
  { id: 'pen-2-14', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Roubo qualificado (lesão grave ou morte).',
    v: 'Quando da violência resulta lesão corporal grave ou morte.', b: null, c: true,
    n: 'A revisão diz que a pena "aumenta de 2/3" nesses casos; no CP o § 3º do art. 157 traz penas próprias. Conferir.' },
  { id: 'pen-2-15', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Extorsão x roubo.',
    v: 'No roubo o agente toma o bem. Na extorsão a vítima é constrangida a fazer algo (ex.: transferir via PIX): o comportamento dela é indispensável.', b: null },
  { id: 'pen-2-16', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Extorsão mediante sequestro: qualificadoras.',
    v: 'Sequestro por mais de 24 h, vítima menor de 18 ou maior de 60, cometido por bando ou quadrilha, ou resultado lesão grave ou morte.', b: null },
  { id: 'pen-2-17', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Estelionato x apropriação indébita.',
    v: 'Estelionato: a fraude vem antes e leva a vítima a entregar. Apropriação: a posse é legítima e a intenção de se apropriar surge depois.', b: null },
  { id: 'pen-2-18', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Quem participou do furto pode responder por receptação do mesmo bem?',
    v: 'Não. A receptação é crime acessório e não é praticada por quem concorreu para o crime anterior.', b: null },
  { id: 'pen-2-19', d: 'Direito Penal', r: 2, t: 'Crimes contra o patrimônio',
    f: 'Dano qualificado: hipóteses.',
    v: 'Violência ou grave ameaça, substância inflamável ou explosiva, contra patrimônio público (inclusive SEM e concessionária) ou por motivo egoístico ou com prejuízo considerável.', b: null },

  // ── Revisão 3 ──
  { id: 'pen-3-01', d: 'Direito Penal', r: 3, t: 'Crimes contra a Administração',
    f: 'Peculato culposo: efeito da reparação do dano.',
    v: 'Antes da sentença irrecorrível: extingue a punibilidade. Depois: reduz a pena pela metade.', b: null },
  { id: 'pen-3-02', d: 'Direito Penal', r: 3, t: 'Crimes contra a Administração',
    f: 'Corrupção ativa x passiva x concussão.',
    v: 'Ativa: particular oferece ou promete (crime comum). Passiva: funcionário solicita, recebe ou aceita promessa. Concussão: funcionário exige. Todos formais.', b: null,
    p: 'Verbo-chave: concussão = EXIGIR.' },
  { id: 'pen-3-03', d: 'Direito Penal', r: 3, t: 'Crimes contra a Administração',
    f: 'Prevaricação: consumação.',
    v: 'Com o retardamento, a omissão ou a prática indevida do ato de ofício para satisfazer interesse ou sentimento pessoal, ainda que o interesse não seja satisfeito.', b: null },
  { id: 'pen-3-04', d: 'Direito Penal', r: 3, t: 'Crimes contra a Administração',
    f: 'Favorecimento real x pessoal.',
    v: 'Real: esconde o proveito do crime. Pessoal: esconde a pessoa do criminoso.', b: null },
  { id: 'pen-3-05', d: 'Direito Penal', r: 3, t: 'Crimes contra a dignidade sexual',
    f: 'Estupro de vulnerável: consentimento da vítima importa?',
    v: 'Não: conjunção carnal ou ato libidinoso com menor de 14 anos é crime, irrelevante consentimento, experiência ou relacionamento.', b: null },
  { id: 'pen-3-06', d: 'Direito Penal', r: 3, t: 'Crimes contra a dignidade sexual',
    f: 'Penas do estupro de vulnerável após a Lei 15.280/2025.',
    v: 'Base de 10 a 18 anos; com lesão grave, 12 a 24; com morte, 20 a 40. Vedada a atenuante da idade (menor de 21 ou maior de 70).', b: 'Lei 15.280/2025' },
  { id: 'pen-3-07', d: 'Direito Penal', r: 3, t: 'Crimes contra a dignidade sexual',
    f: 'Importunação sexual x assédio sexual.',
    v: 'Importunação: ato libidinoso contra alguém sem anuência (ex.: beijo forçado). Assédio: constranger para obter favor sexual valendo-se de superioridade hierárquica; consuma-se com o assédio; +1/3 se a vítima é menor de 18.', b: null },
  { id: 'pen-3-08', d: 'Direito Penal', r: 3, t: 'Crimes contra a dignidade sexual',
    f: 'Aumentos gerais dos crimes sexuais.',
    v: '1/4 em concurso de 2 ou mais pessoas; 1/2 se o agente é ascendente, padrasto, tio, cônjuge, empregador etc., ou se resulta gravidez; 1/3 a 2/3 no estupro em concurso de 2 ou mais agentes ou para controlar o comportamento social ou sexual da vítima.', b: null },
  { id: 'pen-3-09', d: 'Direito Penal', r: 3, t: 'Crimes contra a fé pública',
    f: 'Falsidade ideológica x material.',
    v: 'Ideológica: informação falsa em documento verdadeiro. Material: falsificação física, criando ou alterando o documento.', b: null },
  { id: 'pen-3-10', d: 'Direito Penal', r: 3, t: 'Legislação penal especial',
    f: 'Tráfico privilegiado: requisitos e natureza.',
    v: 'Primário, bons antecedentes, sem dedicação a atividades criminosas nem organização criminosa: reduz de 1/6 a 2/3. Não é equiparado a hediondo.', b: null },
  { id: 'pen-3-11', d: 'Direito Penal', r: 3, t: 'Legislação penal especial',
    f: 'Interrogatório no rito da Lei de Drogas.',
    v: 'Para o STJ, prevalece o art. 400 do CPP: interrogatório é o último ato da instrução.', b: 'art. 400 CPP' },
  { id: 'pen-3-12', d: 'Direito Penal', r: 3, t: 'Legislação penal especial',
    f: 'Violência doméstica contra a mulher admite transação ou sursis processual?',
    v: 'Não. Não se aplica a Lei 9.099/95.', b: 'Súmula 536 STJ' },
  { id: 'pen-3-13', d: 'Direito Penal', r: 3, t: 'Legislação penal especial',
    f: 'Medidas protetivas da Lei Maria da Penha: prazo do juiz.',
    v: '48 horas para decidir as medidas, encaminhar a ofendida à assistência jurídica, comunicar o MP e determinar a apreensão de arma do agressor.', b: 'Lei 11.340/2006' },
  { id: 'pen-3-14', d: 'Direito Penal', r: 3, t: 'Legislação penal especial',
    f: 'Crimes hediondos: o que é vedado e prazo da temporária.',
    v: 'Rol taxativo; inafiançáveis e insuscetíveis de graça e anistia. Prisão temporária de 30 dias, prorrogáveis por igual período.', b: 'art. 5º, XLIII, CF; Lei 8.072/1990' },
  { id: 'pen-3-15', d: 'Direito Penal', r: 3, t: 'Legislação penal especial',
    f: 'Abuso de autoridade: efeitos da condenação automáticos x não automáticos.',
    v: 'Automático: obrigação de indenizar, com valor mínimo fixado a pedido do ofendido. Não automáticos (exigem reincidência): inabilitação de 1 a 5 anos e perda do cargo.', b: null, c: true,
    n: 'A revisão identifica a lei como "8.072/1990", que é a Lei dos Crimes Hediondos. Conferir o número da Lei de Abuso de Autoridade.' },
  { id: 'pen-3-16', d: 'Direito Penal', r: 3, t: 'Execução penal',
    f: 'Remição: quanto se reduz por estudo e por trabalho?',
    v: '1 dia de pena a cada 12 horas de estudo ou a cada 3 dias de trabalho. A remuneração do preso não pode ser menor que 3/4 do salário mínimo.', b: 'Lei 7.210/84' },
  { id: 'pen-3-17', d: 'Direito Penal', r: 3, t: 'Execução penal',
    f: 'Progressão de regime: percentuais.',
    v: 'Sem violência: 16% (primário), 20% (reincidente). Com violência: 25%, 30%. Hediondo: 40%, 60%. Hediondo com morte: 50%, 70%. Feminicídio: 55% (primário). Com morte e feminicídio, sem livramento condicional.', b: null },
  { id: 'pen-3-18', d: 'Direito Penal', r: 3, t: 'Execução penal',
    f: 'Livramento condicional: frações.',
    v: 'Pena de 2 anos ou mais; mais de 1/3 (não reincidente em doloso e bons antecedentes), mais da metade (reincidente em doloso), mais de 2/3 (hediondo, tortura, tráfico, tráfico de pessoas e terrorismo, se não reincidente específico). Sem falta grave nos últimos 12 meses.', b: 'art. 83 CP' },
  { id: 'pen-3-19', d: 'Direito Penal', r: 3, t: 'Execução penal',
    f: 'Exame criminológico obrigatório: para quem?',
    v: 'Para condenados por crimes sexuais e de violência contra a mulher, na progressão e em benefícios como a saída temporária.', b: 'art. 119-A LEP (Lei 15.280/2025)' }
]);
